### ISSUE TITLE
Can't decode small Data Matrix (~10mm)

### ISSUE THREAD

**Issue by giuseppepaul** [zxing-js/library#100]
Hello! I'm trying to use the library to scan a data matrix but I can't seem to get a read at all. It's all working fine for QR codes. I know in the Readme it mentions that there is no documentation for data matrix scanning. 

Is there something different that I need to be doing in the setup?

Thanks!

**Comment by odahcam** [comment]
Are you using it on the browser?

**Comment by giuseppepaul** [comment]
Yes, in browser.

**Comment by odahcam** [comment]
Yeah, we've made an implementation of `BrowserMultiFormatReader` here: https://github.com/zxing-js/ngx-scanner/blob/master/src/app/modules/zxing-scanner/browser-multi-format-reader.ts

Please note that this code reader was made based on a custom `BrowserCodeReader`, so it may be different from the original here, I plan to bring these modification to the browser-layer in a near future.

To enable the multi format reading we use `hints` for this guy:

```typescript
import { Result, DecodeHintType, BarcodeFormat } from '@zxing/library';

const formats =  [BarcodeFormat.QR_CODE, BarcodeFormat.DATA_MATRIX /* so on... */ ];

const hints = new Map<DecodeHintType, any>();

hints.set(DecodeHintType.POSSIBLE_FORMATS, formats);

const codeReader = new BrowserMultiFormatReader(hints);
```

Hope it helps!

**Comment by giuseppepaul** [comment]
Brilliant, thanks a lot @odahcam !

I hope you don't mind me throwing another quick question at you! I have it working well on a webcam, but on an iPhone there seems to be an issue with scanning the very small data matrix codes (they're tiny - around 10mm x 10mm). I think this could be something to do with the resolution of the iPhone camera being very high and the area of the rectangle being too small to be detected?

Thanks
Giuseppe

**Comment by odahcam** [comment]
Thanks!

I never tryied to do something like that with the iPhone camera, but iPhone 8 always have some impressive results while scanning the QRs, I think the size vs. resolution should be the smaller of it's problems. 🤔

**Comment by giuseppepaul** [comment]
I'm using an iPhone 7. I have a slightly bigger matrix, maybe 15mm X 15mm that it reads okay. But the smaller version it doesn't work with at all.

**Comment by odahcam** [comment]
I know that for QR codes, the minimum recomended size is of 20mm², maybe the same aplies to DataMatrix. If you're trying to read the code from a computer screen, well, I won't work at that size, but a physical DataMatrix at 10mm should be possible to decode.

**Comment by giuseppepaul** [comment]
I'm struggling to work this out @odahcam - on my webcam I can get a read, and on an iPad with a 6MP camera it'll work too, but on a 12MP iPhone camera it won't work at all.

Feels like it should be something to do with the area of detection and related to the resolution in some way?

Something in here?

https://github.com/zxing-js/library/blob/master/src/core/common/detector/WhiteRectangleDetector.ts

**Comment by odahcam** [comment]
Well, this could be a bug, but to know that we gotta figure out how to test it first.

**Comment by giuseppepaul** [comment]
I found that if I comment out the code in WhiteRectangleDetector.js that is halving the size of the image (which is being done for performance reasons I assume)... and then hold very still with the barcode in the very centre of the image then it scans.

To test, all I did was create a few codes here:
https://barcode.tec-it.com/en/DataMatrix

Printed them, (they're actually 6mm X 6mm not 10mm) and created a quick browser based demo, tested using an iPhone 7.

**Comment by odahcam** [comment]
That's a very sensible question, maybe some "enable high quality scan" could be created to enable decoding images without changing its source.

**Comment by stevesum** [comment]
Is there any progress in this issue?
We have same problem in our project.
The package fail with the small 2DMatrix codes, but you can't go closer with the camera, because the minimal focus distance.

**Comment by odahcam** [comment]
Now, on version v0.15.0 you can control the device's constraints. Also, I was wondering if maybe returning the media stream would be useful for advanced projects. Anyway, you can decode directly from you own requested media stream object. That said, now is possible to control anything - available in the browser - in the stream.

**Decoding from custom constraints:**

https://github.com/zxing-js/library/blob/2f6503eab60838998836e534524b158c58761e7d/src/browser/BrowserCodeReader.ts#L326-L340

**Decoding from stream:**

https://github.com/zxing-js/library/blob/2f6503eab60838998836e534524b158c58761e7d/src/browser/BrowserCodeReader.ts#L342-L358
