### ISSUE TITLE
Multiple scans forces browser to reload

### ISSUE THREAD

**Issue by thixxsuckz** [zxing-js/library#108]
Hello,
when trying to scan multiple times (about 15-20) the scanner crashes and forces the browser to relaod the page. This happens also in your [demo implementation](https://zxing-js.github.io/library/examples/barcode-camera/) when you start and reset the scanner.
In my applicatin it is necessary to scan multiple times without reloading the page because of an authorization that get lost while reloading.
Is there anyway you can fix that?

Thanks in advance!

Edit: 
Tested on an iPad.

**Comment by odahcam** [comment]
I never saw this happening, can you provide more information? Error message, etc.?

**Comment by odahcam** [comment]
@mc-suchecki have you experienced this issue too?

**Comment by mc-suchecki** [comment]
I didn't try to use the scanner like described above, I've just linked those issues as both seem to be related to some problems while resetting the BrowserCodeReader. You can easily crash the code by opening the demo on Edge and clicking reset button though.
