### ISSUE TITLE
Problems with restarting the scanner on Edge

### ISSUE THREAD

**Issue by mc-suchecki** [zxing-js/library#111]
Reproduction steps:
1. Open QR reader demo: [link](https://zxing-js.github.io/library/examples/qr-camera/)
2. Click on scan - reader is displayed normally.
3. Click on reset - reader is hidden, but:
a) There is an error in the console: SCRIPT5022: SCRIPT5022: InvalidAccessError
b) Clicking on 'start' is not opening the reader again.

I didn't test other demos so far. However, I don't think that it's QR reader-specific, because I've experienced similar problems with a custom reader (QR + EAN-13). 

FYI: I've had similar problems (same error in console) when I called ```BrowserCodeReader.decodeFromInputVideoDevice``` method before video element was created in DOM.

Browser information:
Microsoft Edge 41.16299.666.0
Microsoft EdgeHTML 16.16299

**Comment by mc-suchecki** [comment]
Could be related to #108

**Comment by mc-suchecki** [comment]
Seems to be fixed in 0.12.3!

**Comment by odahcam** [comment]
Thanks for the patience @mc-suchecki , if you think it's not fixed feel free to reopen the issue, we still have things to do about the restarting system.
