### ISSUE TITLE
How to build zxing-js from ts into js and host all files locally

### ISSUE THREAD

**Issue by carylewis** [zxing-js/library#116]
After cloning the repo, I am able to use the examples, but I would like be able to build the library into js and then host the file locally.

The examples currently pull index.min.js from https://unpkg.com/@zxing/library@0.7.0-dev.058aea/umd

I tried to run 

`webpack` ./webpack.config.js bundle.js

but that resulted in numerous errors.

So, I apologize for such a basic question, but how to I compile the .ts files into a bundled .js file?

**Comment by odahcam** [comment]
Give a try: `yarn && yarn build` or `npm i && npm run build`.
