### ISSUE TITLE
How to decode inverse Data Matrix Codes

### ISSUE THREAD

**Issue by JanKhstll** [zxing-js/library#135]
Hello, 

is there any parameter I can set to decode an inverse Data Matrix Code. With inverse I mean that the border color is white and the Data Matrix Code is on a black background. 

I tried this on a printed version of the inverted Data Matrix Code, when inverting the colors manually the detection worked again flawlessly. Inverted Data Matrix Code are allowed as part of ECC 200. 

Unfortunately for my project I have to deal with those inverted Data Matrix Code.

Thank you in advance.

**Comment by odahcam** [comment]
Hello Jan, are you making use of the `LuminanceSource`?

**Comment by JanKhstll** [comment]
Hello, 

thank you for your fast response. 

Unfortunately I am using the UMD version with live camera. The code is similar to your example on https://zxing-js.github.io/library/examples/qr-camera/. 

How can I use the LuminanceSource in this case? I didn't find anything about it in the other examples either.

**Comment by odahcam** [comment]
Well, in this case you will need to extend the `BrowserDataMatrixReader` and override the method [`createBinaryBitmap`](https://github.com/zxing-js/library/blob/303c8a0332f97ddca8707f2e89778a032afc6a99/src/browser/BrowserCodeReader.ts#L357) to be able to invert the luminance source.

I though we had a `hint` for that kind of need, but it ended that I couldn’t find anything about it, so sorry, that's the only way I can tell 100% sure it will work.

If you want to try, you can try to setup the [`BrowserMultiFormatCodeReader`](https://github.com/zxing-js/library/blob/0624865a617adca691734df06062bd525542df33/src/browser/BrowserMultiFormatReader.ts#L7) with the `tryHarder` and `BarcodeFormat.DATA_MATRIX` hints, I have a vague memory that it makes the multi-format try at least one time decoding the code with a inverted luminance source, but no sure.

**Comment by JanKhstll** [comment]
Hello, 

I think I managed that it also works on inverted Data Matrix Codes. 
Thank you very much for your help.

**Comment by odahcam** [comment]
You are welcome!

**Comment by odahcam** [comment]
Could you share how you made it work, just for future reference?

**Comment by Gedoba** [comment]
I'm facing similar issue, but I have to deal with both inverted and normal live video feed. If you could post your solution it'd be great!

**Comment by JanKhstll** [comment]
I followed your suggestion, but instead of overriding the method I just extended it, that was enough for my case. 
In `src/browser/BroswerCodeReader.ts` I adjusted the `createBinaryBitmap` method:

``` 
   protected createBinaryBitmap(mediaElement: HTMLVisualMediaElement): BinaryBitmap {

      if (undefined === this.canvasElementContext) {
        this.prepareCaptureCanvas();
      }

      this.drawImageOnCanvas(this.canvasElementContext, mediaElement);

      const luminanceSource = new HTMLCanvasElementLuminanceSource(this.canvasElement);
      // This is the line I added
      const invertedLuminance = luminanceSource.invert()
      const hybridBinarizer = new HybridBinarizer(invertedLuminance);

      return new BinaryBitmap(hybridBinarizer);
    }
```

After that I re-created the `index.min.js` with `npm run build`. After that the detection worked on inverted data matrix codes. 

I assume there are also more sophisticated ways to achieve this but I hope it helps you to find your way.

**Comment by odahcam** [comment]
The idea is to do that modification, but not to edit the library sources because this can block you from getting futher updates or even lost your code if you changed something inside `node_modules`. So, you would do the exactly same method but in a class created by you that extends the original `BrowserCodeReader`, this would override the method as you need and not impact with the library usage.

**Comment by Gedoba** [comment]
Yes, I did exactly as you suggested:

`// defining own class that extends normal scanner
// it inverts the image before making the scan
class BrowserMultiFormatReaderInverse extends BrowserMultiFormatReader {
    createBinaryBitmap(mediaElement) {
        if (undefined === this.canvasElementContext) {
            this.prepareCaptureCanvas();
        }

        this.drawImageOnCanvas(this.canvasElementContext, mediaElement);

        const luminanceSource = new HTMLCanvasElementLuminanceSource(this.canvasElement);
        const invertedLuminance = luminanceSource.invert()
        const hybridBinarizer = new HybridBinarizer(invertedLuminance);

        return new BinaryBitmap(hybridBinarizer);
    }
}`

My only issue is that I'm decoding from instances of inverse and normal reader at the same time. On PC it works OK, but on iOS it asks me two times for permission and only one of the reader works (the first one I'm starting decoding from).

I might have to let user choose if it's black on white or inverse.

**Comment by Gedoba** [comment]
I'm changing state every 1.2s and depending on it I'm using inverse bitmap or normal one. This seems to be working.
