### ISSUE TITLE
Super Confusing for Node JS - Read Barcode from URL on server side - IMPOSSIBLE?

### ISSUE THREAD

**Issue by ezos86** [zxing-js/library#136]
Scans are uploaded as images and then I need to read the images and get the code from the image, but it seems so odd the library has capability to do this on browser but can't on server side Node. 

Documentation is extremely extremely confusing. Please help - no luck after hours of trying to use it.

**Comment by odahcam** [comment]
The lib is built and tested with Node, so I'd say it is the easiest way to use it. 
I couldn't understand what you are trying to do, but the library is not tested against decoding from URL in browser and if you really want an detailed explanation on why it is not that simple, I can take some time to write it. I will be happy to help once I understand how you are trying to use this library.
If you want to take a deep look on how things work you can take a look on the original library which this project aims to port, https://github.com/zxing/zxing, or just take a look at the sources, which are documented.
Sorry about the lack if documentation, it happens that I can only code or document, I don't have enough time for both.

**Comment by ezos86** [comment]
Thanks for the quick reply.

I would expect:

const codeReader = new ZXing.decodeImage

to work in node, but it only works in browser.

**Comment by ezos86** [comment]
I see the BrowserQRCodeReader(), and probably be better to not have this label, if this is the method to also read barcodes, not just QR - from my understanding of the documentation. 

I would expect it to be:
```
const codeReader = new ZXing.barcodeReader();
codeReader.decode('IMAGE URL')
```
Running most of the methods throw errors because there is no DOM.

**Comment by odahcam** [comment]
Browser layer (`Browser` prefixed classes) depends on `window` and DOM APIs, so you can't use it on server-side. Try using something like that ([found here](https://github.com/zxing-js/library/blob/master/README.md#use-outside-the-browser-with-commonjs)):

```typescript
const { MultiFormatReader, BarcodeFormat } = require('@zxing/library/esm5'); // use this path since v0.5.1

const hints = new Map();
const formats = [BarcodeFormat.QR_CODE, BarcodeFormat.DATA_MATRIX/*, ...*/];

hints.set(DecodeHintType.POSSIBLE_FORMATS, formats);

const reader = new MultiFormatReader();

reader.setHints(hints);

const imgByteArray = /* your logic to download your image before decoding */;

const luminanceSource = new RGBLuminanceSource(imgWidth, imgHeight, imgByteArray);
const binaryBitmap = new BinaryBitmap(new HybridBinarizer(luminanceSource));

reader.decode(binaryBitmap);
``` 

`BrowserQRCodeReader` scans only QR codes, there are other readers for other code types, like this on in this example from README above.

**Comment by ezos86** [comment]
Understood, all examples have the BrowserQRCodeReader. Probably confused by that some.

I have no idea what that is doing, where I would put in the image url. It looks like it's generating a Bitmap? I tried that snippet for CommonJS, that's what I felt was very very confusing. It seems way more complicated to use server side for some reason. 

So do I need to do the hints?
How could this take an image given to it?

I will be more than happy to contribute to documentation - once I figure this out.

**Comment by ezos86** [comment]
Yeah, still several issues. 

Decoder not defined, then removed that and then 

```
ReferenceError: RGBLuminanceSource is not defined
```

**Comment by odahcam** [comment]
A functional code would be something like that, but I can't promise it will work with `axios` byte arays, it's jsut an example of what I'm talking about:

```typescript
const { 
  MultiFormatReader, 
  BarcodeFormat,
  DecodeHintType,
  RGBLuminanceSource, 
  BinaryBitmap,
  HybridBinarizer
} = require('@zxing/library/esm5'); // use this path since v0.5.1

const axios = require('axios');
  
const hints = new Map();
const formats = [BarcodeFormat.QR_CODE, BarcodeFormat.DATA_MATRIX/*, ...*/];

hints.set(DecodeHintType.POSSIBLE_FORMATS, formats);

const reader = new MultiFormatReader();

reader.setHints(hints);

async function decodeFromUrl(url, width, height) {
  
  const response = await axios.get(url, {
    responseType: 'arraybuffer'
  });
  
  const luminanceSource = new RGBLuminanceSource(width, height, new Uint8ClampedArray(response.data));
  const binaryBitmap = new BinaryBitmap(new HybridBinarizer(luminanceSource));
  
  try {
    reader.decode(binaryBitmap);
  } catch (e) {
    console.error(e)
  }

}

decodeFromUrl('https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/QR_code_for_mobile_English_Wikipedia.svg/480px-QR_code_for_mobile_English_Wikipedia.svg.png', 480, 480);
decodeFromUrl('https://upload.wikimedia.org/wikipedia/commons/5/5b/Qr-1.png', 220, 220);
decodeFromUrl('https://upload.wikimedia.org/wikipedia/commons/2/2d/Qr-3.png', 220, 220);
decodeFromUrl('http://www.codigos-qr.com/wp-content/uploads/2018/06/datamatrix-generator.png', 200, 200)
```

**Comment by odahcam** [comment]
Closing as no follow up.

**Comment by ywachao** [comment]
i user it like this,i get an error, it's show  NotFoundException: No MultiFormat Readers were able to detect the code.

**Comment by ywachao** [comment]
> A functional code would be something like that, but I can't promise it will work with `axios` byte arays, it's jsut an example of what I'm talking about:
> 
> ```ts
> const { 
>   MultiFormatReader, 
>   BarcodeFormat,
>   DecodeHintType,
>   RGBLuminanceSource, 
>   BinaryBitmap,
>   HybridBinarizer
> } = require('@zxing/library/esm5'); // use this path since v0.5.1
> 
> const axios = require('axios');
>   
> const hints = new Map();
> const formats = [BarcodeFormat.QR_CODE, BarcodeFormat.DATA_MATRIX/*, ...*/];
> 
> hints.set(DecodeHintType.POSSIBLE_FORMATS, formats);
> 
> const reader = new MultiFormatReader();
> 
> reader.setHints(hints);
> 
> async function decodeFromUrl(url, width, height) {
>   
>   const response = await axios.get(url, {
>     responseType: 'arraybuffer'
>   });
>   
>   const luminanceSource = new RGBLuminanceSource(width, height, new Uint8ClampedArray(response.data));
>   const binaryBitmap = new BinaryBitmap(new HybridBinarizer(luminanceSource));
>   
>   try {
>     reader.decode(binaryBitmap);
>   } catch (e) {
>     console.error(e)
>   }
> 
> }
> 
> decodeFromUrl('https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/QR_code_for_mobile_English_Wikipedia.svg/480px-QR_code_for_mobile_English_Wikipedia.svg.png', 480, 480);
> decodeFromUrl('https://upload.wikimedia.org/wikipedia/commons/5/5b/Qr-1.png', 220, 220);
> decodeFromUrl('https://upload.wikimedia.org/wikipedia/commons/2/2d/Qr-3.png', 220, 220);
> decodeFromUrl('http://www.codigos-qr.com/wp-content/uploads/2018/06/datamatrix-generator.png', 200, 200)
> ```

i used like this, but it's show NotFoundException: No MultiFormat Readers were able to detect the code.

**Comment by ywachao** [comment]
i used the jsqr.js library has no problem,but why zxing-js always show NotFoundException ?

**Comment by odahcam** [comment]
Please, try revising the way you prepare your data to be decoded and remember I only shared examples in THIS issue, they're never tested in real world scenarios. Also you can take a look in one of our 150+ tests, they all run in Node.js.

**Comment by odahcam** [comment]
I locked conversation because there are proper places for discussion.
