### ISSUE TITLE
Dependency with WTFPL License

### ISSUE THREAD

**Issue by ddramone** [zxing-js/library#140]
One of the dependency (`ts-custom-error`) has a license "WTFPL", This license is not acceptable because of legal and security risks associated with it.

Could you maybe consider fixing it by finding alternative or removing a dependency?

**Comment by odahcam** [comment]
It's used to exend the JavaScript error object, one simple thing which TypeScript couldn't do. If we're lucky TS is already supporting this by this time so it will be easy to drop that lib, otherwise we gonna have to rewrite the wheel once again.
