### ISSUE TITLE
Performance optimizations

### ISSUE THREAD

**Issue by My6UoT9** [zxing-js/library#143]
I got a few milliseconds speedup by changing settings for the canvas:
```
        this.canvasElementContext = canvasElement.getContext('2d', { alpha: false });
        this.canvasElementContext.globalCompositeOperation = 'copy';
```

**Comment by My6UoT9** [comment]
alpha: false should be good.
copy oth is not clear if its better; the default should be faster (source-over) apparently, but I will use this on a ipad, there copy was much faster.
https://jsperf.com/globalcompositeoperation/8

**Comment by odahcam** [comment]
You can PR this if you want. :)

Maybe copy was faster on iPad due to some Safari optimisation.

**Comment by My6UoT9** [comment]
Made a PR for the transparency, I think the globalCompositeOperation change would require somekind of layer inbetween, taking the best option for each platform; while this can change with each browser/os update.

**Comment by odahcam** [comment]
Maybe could be configurable.
