### ISSUE TITLE
Does not work in Safari

### ISSUE THREAD

**Issue by Osirys25** [zxing-js/library#147]
There is strage issue in Safari 11+ on IPhones.
There are no errors in browser's console but QR scan is not performed.
Could someone help with this?
Could someone resolve this issue in further app release?

On android everything seems to work fine.

**Comment by katanagari7c1** [comment]
I've just made this demo app:
https://katanagari7c1.github.io/zxing-test/

Tested on iPad with iOS 12 and worked fine. Can you reproduce your issue with my project?

**Comment by zenboss** [comment]
> I've just made this demo app:
> https://katanagari7c1.github.io/zxing-test/
> 
> Tested on iPad with iOS 12 and worked fine. Can you reproduce your issue with my project?

Sorry, katanagari7c1. your demo has the same problem, I'm unable to use my iPad's camera in  your demo.

**Comment by odahcam** [comment]
Does https://zxing-js.github.io/ngx-scanner/ works for you guys?

**Comment by odahcam** [comment]
I'm closing as this had no follow up.

**Comment by EyadAlghamdi** [comment]
> Does https://zxing-js.github.io/ngx-scanner/ works for you guys?

do you have the source code for this? it works on my IOS safari but the official demo on https://zxing-js.github.io/library/ doesnt seem to work for iphone

Thank you

**Comment by odahcam** [comment]
There's the source code: https://github.com/zxing-js/ngx-scanner

Remember that on iPhone it only works on Safari, it does not work on any other browser.
