### ISSUE TITLE
iOS use always the front camera

### ISSUE THREAD

**Issue by stevesum** [zxing-js/library#149]
Hi,

We try to use the zxing-js on iOS 12 with safari, but always show the front camera (independent you choose any of the videoInputDevice's)

**Comment by stevesum** [comment]
The reason is simple:
navigator.mediaDevices.enumerateDevices() gives back the media devices, but they deviceId is an empty string.

**Comment by odahcam** [comment]
You sure you have the right permissions?

**Comment by stevesum** [comment]
Yes. It is asked for the permission and I gave it.
And if I call the decodeFromInputVideoDevice(undefined, 'video') then works

**Comment by Matth--** [comment]
I am having the same issue. Problem started last week. @stevesum have you already been lucky in finding a solution?

**Comment by PabloAH** [comment]
Same here, I tried replacing the deviceIds that are "" with plain undefined to decodeFromInputVideoDevice hoping it'll use the "facingMode" constraint but still not working (I don't really have an iPhone to debug more)

**Comment by YouriHugoBos** [comment]
Same issue for me, tried a lot of things to change the facing mode, no luck..

**Comment by samuelting** [comment]
**Observation**

Hi there, I have a testing iPhone and come across the same issue. Maybe I can help in this issue. 

The root cause of issue is because of the different way iOS and Android and handle the official HTML5 API call ```navigator.mediaDevices.enumerateDevices()```. 

In iOS, the hardware device info will not be disclosed until the user accept camera access request.

<img width="654" alt="before_permission_accepted" src="https://user-images.githubusercontent.com/5226878/56489565-b3b14000-6514-11e9-9039-ef06ea9f3f48.png">

After the user accept the access request, I can fetch the device id of my device.

<img width="976" alt="after_permission_accepted" src="https://user-images.githubusercontent.com/5226878/56490038-5f0ec480-6516-11e9-8c54-889374b5083c.png">

In Android, i can view the deviceId of my camera no matter whether camera permission is granted or not.

<img width="726" alt="android_permission" src="https://user-images.githubusercontent.com/5226878/56490223-068bf700-6517-11e9-888f-74b8e3d4d483.png">

**A thought on the use case**

@PabloAH I have tried settings on my iPhone, by setting deviceId as plain ```undefined```, I can force zxing-js to open camera in "environment" facing mode. If your application does not allow the user to choose which camera to use, it is an option.

Remarks: 
Testing Devices Model 
Nexus 6 (Android 7.1.1)
iPhone SE (iOS 12.2)

My testing code to fetch deviceId for your reference:
```
navigator.mediaDevices.enumerateDevices().then(videoInputDevices => {
        videoInputDevices.forEach(device =>
            console.log(device)
        );
    })
```

**Comment by PabloAH** [comment]
Thanks @samuelting for the information!

I don't have an iPhone yet to confirm but the sequence makes sense in Android, I just request "undefined" at first, and once the camera is accepted (there is no event in the library but you can use $("#video").on("playing")) I go and get the list of specific cameras to add the drop down.

So this is likely not a problem with the library, but just a correction has to be made on the samples.

**Comment by flemx** [comment]
Thanks @samuelting , initiating with undefined works for me for using the back camera.

Another workaround which I was using before, was to call the native navigator.mediaDevices.getUserMedia function first so the camera access can be accepted, after which the deviceID can be set using "navigator.mediaDevices.enumerateDevices()".

The "decodeFromInputVideoDevice" can then be initiated with the deviceID, this could be a workaround if you have a requirement for switching between cameras.

```
           let selectedDeviceId;
           navigator.mediaDevices.getUserMedia({video:true})
           .then(function(stream){
                console.log('Stream1 started with success');
                setDevice();
            })
            .catch(function(){ 
                console.log('Failed to start stream1')
            });
            
            setDevice();
            function setDevice(){
                navigator.mediaDevices.enumerateDevices()
                .then(function(devices){
                    console.log('Getting device');
                    console.log(devices[1]);
                    selectedDeviceId = devices[1].deviceId
                })
                .catch(function(){
                    console.log('getting device failed');
                  })
               }
```

**Comment by odahcam** [comment]
Well, `enumerateDevices` was precisely chosen because it used to allow us to get the devices info along with their ID **without** asking permissions, looks like that not anymore. Why? because the component could load all the available devices before bothering the user with permission modals.

The solution I propose is to forget about enumerating devices and properly ask the user for permissions before using any. 

Also, I noticed that every time I switch cams in MacBook, the scanner has to ask for permissions again and again and that didn't happened before too. That's another thing I wanna solve.

**Comment by odahcam** [comment]
As posted [here](https://github.com/zxing-js/library/issues/152#issuecomment-495412501), this may be a workaround:

```TS
  ngOnInit(): void {
    this.scanner.camerasFound.subscribe((devices: MediaDeviceInfo[]) => {

      this.availableDevices = devices;

      // selects the devices's back camera by default
      for (const device of devices) {
          if (/back|rear|environment/gi.test(device.label)) {
              this.scanner.changeDevice(device);
              this.currentDevice = device;
              break;
          }
      }
    });
  }
```

**Comment by pepeh** [comment]
@odahcam 
How to use this fix with this example https://zxing-js.github.io/library/examples/qr-camera/ ?
Or it should be some different library?

**Comment by markestocapio** [comment]
@odahcam 

Thanks for the update. Since I don't need the user to choose between camera source. I manage to force using the back camera. But I still need to check if currentDevice.deviceId = undefined; 

For now, this workaround works for us.  Thanks

**Comment by vlagrawal** [comment]
Zxing-js plugin default code is working in ios iPhone 6 or more updated version.

**Comment by odahcam** [comment]
@pepeh 

```javascript
// on line 121 we have...
      codeReader.getVideoInputDevices()
        .then((videoInputDevices) => {
        // so you just need to filter available devices on the first line and it shall help you understand
        videoInputDevices = videoInputDevices.filter(device => {
            if (/back|rear|environment/gi.test(device.label)) {
                return device
            }
        })
```

**Comment by odahcam** [comment]
@arthurmmedeiros você percebeu que, nesse trecho de código, em nenhum momento você está passando o `deviceId` para a biblioteca?

Você deveria tentar algo como:

```js
function decodeNow() {
    if (deviceId && !isOpen) {
        multiReader.decodeFromInputVideoDeviceContinuously(deviceId, 'video', callbackResult)
            .then((res: any) => {
                console.log('called then');
            })
            .catch((err: any) => console.error(err));
    }
}
```

**Comment by arthurmmedeiros** [comment]
@odahcam eu retirei o "deviceId" pra testar o que ele faria quando envio "null" no parâmetro. Eu havia criado uma tela antes da câmera pra selecionar o deviceId, guardei na global store e abria a câmera. Isso nunca funcionou. Você tem uma forma de selecionar a câmera que funciona legal?

**Comment by odahcam** [comment]
Bom, vou te mandar um exemplo pra ti ver uma forma de se fazer.

Tenho esse cara em Angular que faz basicamente isso: https://stackblitz.com/edit/zxing-ngx-scanner
Ele roda em cima dessa biblioteca: https://github.com/zxing-js/ngx-scanner

Se a gente olhar no código-fonte, eu seleciono as câmeras de uma forma completamente customizada: 

https://github.com/zxing-js/ngx-scanner/blob/a28b478530e9ed8b94b35ae0aa534b84385de5ce/projects/zxing-scanner/src/lib/zxing-scanner.component.ts#L688-L705

Eu reescrevi isso tudo nessa nova biblioteca porquê na época essa lib aqui não funcionava bem, mas se você ler o código vai ver que é basicamente a mesma coisa que tem aqui hoje, eu copiei de lá pra cá.

Pelo que eu entendi você quer algo tipo isso (exemplo **bem** simples): https://stackblitz.com/edit/zxing-scanner-react?file=Hello.js

**Comment by arthurmmedeiros** [comment]
> Bom, vou te mandar um exemplo pra ti ver uma forma de se fazer.
> 
> Tenho esse cara em Angular que faz basicamente isso: https://stackblitz.com/edit/zxing-ngx-scanner
> Ele roda em cima dessa biblioteca: https://github.com/zxing-js/ngx-scanner
> 
> Se a gente olhar no código-fonte, eu seleciono as câmeras de uma forma completamente customizada:
> 
> https://github.com/zxing-js/ngx-scanner/blob/a28b478530e9ed8b94b35ae0aa534b84385de5ce/projects/zxing-scanner/src/lib/zxing-scanner.component.ts#L688-L705
> 
> Eu reescrevi isso tudo nessa nova biblioteca porquê na época essa lib aqui não funcionava bem, mas se você ler o código vai ver que é basicamente a mesma coisa que tem aqui hoje, eu copiei de lá pra cá.
> 
> Pelo que eu entendi você quer algo tipo isso (exemplo **bem** simples): https://stackblitz.com/edit/zxing-scanner-react?file=Hello.js

Era esse exemplo mesmo que eu precisava @odahcam valeu!!!

**Comment by odahcam** [comment]
Nada, boa sorte. 🖖

**Comment by jasoncapriati** [comment]
Hello!

`mediaDevices.enumerateDevices()` returns an array of _connected_ `MediaDeviceInfo` objects which has properties like `deviceId`, `kind` and `label`.

Safari and iOS Safari do not support this spec [1] yet.

[1] https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo

**Comment by odahcam** [comment]
Well, that's new. I have never notice that and had no idea that was happening, maybe because the script had a very weak flow in some points. I hope to have time to improve this, this chunk of code also needs automated tests asap.
