### ISSUE TITLE
Not working in WKWebView/iOS 11 (e.g. Chrome)

### ISSUE THREAD

**Issue by noru** [zxing-js/library#15]
Since this library relies on `navigator.mediaDevices.getUserMedia` and `mediaDevices` is null in WKWebView browsers, things break.

Notably, Safari is working fine.

It seems to be an [Apple Issue](https://bugs.chromium.org/p/chromium/issues/detail?id=783220&desc=2) and probably nothing can be done here. But I think it should be logged anyhow.

Regards,
Drew

**Comment by odahcam** [comment]
Thanks Drew. I gonna ask @werthdavid to test, because I don't have any Apple devices on hands at the moment. 😉

**Comment by werthdavid** [comment]
That's correct unfortunately. Copied from zxing-js/ngx-scanner#Limitations:
- On iOS-Devices camera access works only in native Safari and not in other Browsers (Chrome,...) or Apps that use an UIWebView or WKWebView. This is not a restriction of this component but of the limited WebRTC support by Apple. The behavior might change in iOS 11.3 (Apr 2018?, not tested) as stated [here](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_11_1.html#//apple_ref/doc/uid/TP40014305-CH14-SW1)

**Comment by odahcam** [comment]
Little update on this: https://github.com/zxing-js/ngx-scanner/issues/149

**Comment by odahcam** [comment]
As stated in [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=752458#c46) iOS 14.3 may finally solve this issue.

**Comment by egfx** [comment]
> As stated in [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=752458#c46) iOS 14.3 may finally solve this issue.

It hasn't iOS 14.4 does not have support for webrtc in chrome.

**Comment by odahcam** [comment]
https://blog.bitsrc.io/ios-14-3-brings-webrtc-to-wkwebview-closing-gap-on-ios-accessibility-90a83fa6bda2
