### ISSUE TITLE
Writing QR code in IE11 and Edge not working as expected

### ISSUE THREAD

**Issue by andreas-aeschlimann** [zxing-js/library#154]
Hello, first of all thanks for this great library.

I implemented scanning and writing QR codes in my Angular 7 app and I have inconsistent results in IE11 and Edge. Scanning QR codes works in all browsers. But when I write/create a QR code, the displayed images are different. In IE11/Edge the result is always an unreadable string.

My code in Angular:

```
const codeWriter = new BrowserQRCodeSvgWriter();
codeWriter.writeToDom(this.qrCode.nativeElement, "Test",  500, 500);
```

I could reproduce the issue when I opened your test page in Edge: https://zxing-js.github.io/library/examples/qr-svg-writer/. When I scan the visible QR code, I get 

`UVIgY29kZSAoYWJicmV2aWF0ZWQgZnJvbSBRdWljayBSZXNwb25zZSBDb2RlKSBpcyB0aGUgdHJhZGVtYXJrIGZvciBhIHR5cGUgb2YgbWF0cml4IGJhcmNvZGUgKG9yIHR3by1kaW1lbnNpb25hbCBiYXJjb2RlKSBmaXJzdCBkZXNpZ25lZCBmb3IgdGhlIGF1dG9tb3RpdmUgaW5kdXN0cnkgaW4gSmFwYW4u`

instead of 

`QR code (abbreviated from Quick Response Code) is the trademark for a type of matrix barcode (or two-dimensional barcode) first designed for the automotive industry in Japan.`

In Internet Explorer, the example page doesn't seem to work at all. It is probably missing polyfills.

What is the reason for this?

EDIT: The output in IE11 and Edge is base64 encoded version of the original string.

**Comment by odahcam** [comment]
> EDIT: The output in IE11 and Edge is base64 encoded version of the original string.

![image](https://user-images.githubusercontent.com/3942006/58373258-8dab0100-7f01-11e9-9130-a91fa90a0cd5.png)

That's funny.

Well, I don't intend to support IE11 at all, but I could do some debugging when I have free time. I'm just glad that just by decoding the string we have a workaround.

**Comment by odahcam** [comment]
> EDIT: The output in IE11 and Edge is base64 encoded version of the original string.

![image](https://user-images.githubusercontent.com/3942006/58373258-8dab0100-7f01-11e9-9130-a91fa90a0cd5.png)

That's funny.

Well, I don't intend to support IE11 at all, but I could do some debugging when I have free time.

**Comment by andreas-aeschlimann** [comment]
I understand, but – unfortunately – in the business world IE11 is still a must have. In my case, this was a deal-breaking issue.

Personally, I was more surprised that Edge behaved differently than FF/Chrome.

**Comment by odahcam** [comment]
Are you using the IE11 polyfills?

**Comment by andreas-aeschlimann** [comment]
I was pretty sure I did, because I used it in an Angular app where IE11 polyfills are necessary to make it run in IE. Is there a specific polyfill that I need for zxing, just to make sure?

**Comment by odahcam** [comment]
There's some, since I don't know what you are using, here is the browser section for you to take a look: https://github.com/zxing-js/library#browser-support

**Comment by andreas-aeschlimann** [comment]
I have these in my (Angular) project:

```typescript
// Angular
import "core-js/es6/symbol";
import "core-js/es6/object";
import "core-js/es6/function";
import "core-js/es6/parse-int";
import "core-js/es6/parse-float";
import "core-js/es6/number";
import "core-js/es6/math";
import "core-js/es6/string";
import "core-js/es6/date";
import "core-js/es6/array";
import "core-js/es6/regexp";
import "core-js/es6/map";
import "core-js/es6/set";

// ZXing
import "core-js/es6/typed";

// Others
import "zone.js/dist/zone"; // Included with Angular CLI.
```

Is it not enough?

The weird thing is that the output of a QR code works, but the content is different. I am not convinced whether a polyfill can fix that.

**Comment by delower-hosen** [comment]
2.1.0 worked for me.
