### ISSUE TITLE
Node.js install w/o Core-JS support, Suppress Warnings

### ISSUE THREAD

**Issue by hotdang-ca** [zxing-js/library#155]
After adding via `npm install @zxing/library` to my React Typescript project, and running the project, I get issued build warnings that don't effect functionality:

```
WARNING in ./node_modules/@zxing/library/esm5/core/common/detector/MathUtils.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../../../../src/core/common/detector/MathUtils.ts': Error: Can't resolve '../../../../src/core/common/detector/MathUtils.ts' in 'C:\Users\jperi\Developer\BrewNinja\StrangeBrewWeb\StrangeBrew.App\node_modules\@zxing\library\esm5\core\common\detector'
```
This happens several times; it's not critical, and I presume it is just a case of not also having `core-js.` About 122kb in total warning logs.

Is there a way these warnings can be suppressed? It's a little noisy, and effects our ability to effectively parse our logs during CI builds.

**Comment by odahcam** [comment]
So this is the file: https://github.com/zxing-js/library/blob/master/src/core/common/detector/MathUtils.ts

I can't find nothing wrong with it. Are you compiling 3th-party TS files?

**Comment by odahcam** [comment]
No following, closing.

**Comment by hotdang-ca** [comment]
Sorry, no notification.
Yes, the entire project is TypeScript and we include `@types` wherever possible.

Issue still persists.
