### ISSUE TITLE
TypeError: Argument 1 of CanvasRenderingContext2D.drawImage could not be converted to any of: HTMLImageElement, SVGImageElement, HTMLCanvasElement, HTMLVideoElement, ImageBitmap.

### ISSUE THREAD

**Issue by luanribeirosv** [zxing-js/library#157]
Hi.

In Firefox, when you start the QR Code reader and reset it without doing any reading this error occurs:

`TypeError: Argument 1 of CanvasRenderingContext2D.drawImage could not be converted to any of: HTMLImageElement, SVGImageElement, HTMLCanvasElement, HTMLVideoElement, ImageBitmap.`

The test was performed on the demo page itself: [https://zxing-js.github.io/library/examples/qr-camera/](https://zxing-js.github.io/library/examples/qr-camera/)

Library version: 0.12.3
Firefox version: 66.0.3

**Comment by odahcam** [comment]
Can you check if this still occours?
