### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by csutorasr** [zxing-js/library#16]
Add CODE-128 support to the readme file.

**Comment by odahcam** [comment]
Are you talking about the [supported formats](https://github.com/zxing-js/library#supported-formats).

**Comment by csutorasr** [comment]
Exactly!

**Comment by odahcam** [comment]
So, Code 128 is already on that table, is there something wrong? 🤔

**Comment by csutorasr** [comment]
#12 is done, but it shows

> (in-progress)

Please update it in the new version.

**Comment by odahcam** [comment]
Updated.
