### ISSUE TITLE
Is there way to include only required modules (qr/barcode/etc)? 

### ISSUE THREAD

**Issue by rozhok** [zxing-js/library#167]
Hey, my app doesn't need the whole lib, only QR code reader.

Is there way to include only required modules so I won't bundle entire 200Kb js into my app?

Thanks,

**Comment by odahcam** [comment]
Just inspect your bundle and see if you can find all that code, as far as I know three shaking should take care of most of it. But still, improving modularity is one of the things we gotta do around here.
