### ISSUE TITLE
Scan start handling

### ISSUE THREAD

**Issue by MaciejJanyska** [zxing-js/library#169]
It is possible to handle scan start event from the camera? I would like to show a preview, only when the scanning has started.

**Comment by odahcam** [comment]
Sorry, I could not understand what you mean with preview.

**Comment by MaciejJanyska** [comment]
Sorry for my imprecise question. I have a modal component in my app which has a `video` element. I would like to show this modal only if video from camera has successfully loaded.

**Comment by odahcam** [comment]
I see, you could display the camera stream in the video by yourself, so you would be able to control any playing or anything else events and then you could just pass the video element to the library so it decodes from the video.

**Comment by odahcam** [comment]
Feel free to open new issues as needed.
