### ISSUE TITLE
Video stream has ended before any code could be detected.

### ISSUE THREAD

**Issue by rybon** [zxing-js/library#177]
When this error is thrown, the camera stream is not closed.

Basically the same issue that was fixed earlier in #158 is back. The `navigator.getUserMedia()` is not closed properly, which can be observed by the red recording icon remaining visible in the browser tab.

**Comment by odahcam** [comment]
I'm planning to implement RxJS or some video stream specific scanner to solve that problems. Maybe #175 solves this or I will have to do more hard work.

**Comment by mathiasfc** [comment]
Any solution?

**Comment by odahcam** [comment]
@luanribeirosv can you still reproduce this error in the current library version?
