### ISSUE TITLE
Image Clean Issue

### ISSUE THREAD

**Issue by ccy0013** [zxing-js/library#180]
At line 898 in src/browser/BrowserCodeReader.ts (in _destroyImageElement function): 

"this.imageElement.src = undefined;"

Set image src attribute to undefined before destroy would send a server call to '/undefined' in iOS Safari. But it works fine in Android Chrome.

Hope it can be fixed for iOS Safari. Thanks!

**Comment by odahcam** [comment]
That's unbelievable, `undefined` is not even a string 🤦‍♂ . Any ideas how Safari would understand it should clean the image object?

**Comment by ccy0013** [comment]
> That's unbelievable, `undefined` is not even a string 🤦‍♂ . Any ideas how Safari would understand it should clean the image object?

Yea, it's weird. But when I tried to set it to an empty string instead, it works good for both iOS Safari and Android Chrome. And it also works for several other browsers under Android (Firefox is not tested yet).
