### ISSUE TITLE
Uncaught (in promise) DOMException in Google Chrome

### ISSUE THREAD

**Issue by shaunwurdeman** [zxing-js/library#184]
When testing in Chrome (v75.0.3770.80) on MacOS the error "Uncaught (in promise) DOMException" is thrown in the console.
This happens on my custom site using the tool, as well as the example page (https://zxing-js.github.io/library/examples/multi-camera/)

This behaviour seems to only be present in Chrome. 
It looks like it could possibly be because of Chrome's autoplay policies?

**Comment by odahcam** [comment]
It could also be a camera access issue related to permissions. I need to know what version of Chrome you're using, operational system and if it's some USB device or built in camera.

**Comment by SaulBurgos** [comment]
I have the same problem... only happen on Chrome on IOS.  

And I found this report of the bugs: 

https://stackoverflow.com/questions/51501642/chrome-and-firefox-are-not-able-to-access-iphone-camera/53093348#53093348

What do you think guys?

**Comment by odahcam** [comment]
This should not work in iOS Chrome, since `getUserMedia` is not suported there, for more info ask Apple, they seem to just avoid allowing other browsers than Safari to implement WebRTC features.

@shaunwurdeman I'll be closing the issue if you don't provide more debug information.

**Comment by shaunwurdeman** [comment]
Hi @odahcam sorry about the delay. At the time of the initial issue I was using Chrome v75.0.3770.80 on MacOS (10.14.5), as mentioned in the issue. The camera is the built in camera on a MacBook Pro (13-inch, Mid 2012).
I've just tested the sample website again on Chrome v75.0.3770.142 and am now getting a "Uncaught ReferenceError: ZXing is not defined". This same error is thrown in Safari v12.1.1 on the same device.
