### ISSUE TITLE
camera identified barcodes

### ISSUE THREAD

**Issue by diginfo** [zxing-js/library#185]
Hi;

Just got this working using a video element and using camera, thanks so much.

Is it possible to have the camera stream html element superimpose a read line through the center of the identified barcode, or a box around it ??

Many thanks again

**Comment by odahcam** [comment]
Hello, thank you!

Currently trough the lib API it not possible, but you could use the [Result](https://github.com/zxing-js/library/blob/master/src/core/Result.ts) data on decode results to draw it yourself, if you wish.
