### ISSUE TITLE
Scan fail on data-matrix

### ISSUE THREAD

**Issue by stevesum** [zxing-js/library#191]
Hi,

We use this library in production, but we get a lot of report about the scanner fail on scan small Data-Matrix codes.

Unfortunatelly the data-matrix has no size limit defined in the standard, therefore on the packages that is usually around 10 mm.

The camera of device can't go close enough to identify these codes.
Is any settings in the plugin what helps on that? (change scan resolution, zoom, anything...)

**Comment by odahcam** [comment]
For now maybe the try harder hint can help. Tell me if you need help with the hints and, if so, the scanner class you're using.

**Comment by stevesum** [comment]
Hi. Yes, the try harder hint is help. May would worth to extend the documentation with the other hint options. Currently contains only the possible formats only.

**Comment by odahcam** [comment]
I agree, and specially think about linking the original library's documentation resources, because it's the same API, just with a bit differences in language syntax.
