### ISSUE TITLE
Not working in safari full screen mode via "Add to homeScreen" widget

### ISSUE THREAD

**Issue by AyeAyeThet** [zxing-js/library#192]
Hello, I would like to know if there's a possibility of supporting full screen mode for IOS devices when I access the website via "Add to home Screen" from safari browser.
When I used meta tag or "display": "standalone" in manifest.json to get full screen. But it does not work and **"Can't enumerate devices, method not supported."** appeared.I used the codes from https://zxing-js.github.io/library/examples/qr-camera/.
Thanks and Regards

**Comment by odahcam** [comment]
Dupe of #15
