### ISSUE TITLE
Pass hints to constructor client side 

### ISSUE THREAD

**Issue by shaunwurdeman** [zxing-js/library#193]
Hi, how can we pass hints to a BrowserMultiFormatReader constructor being called from client side JS?

The below doesn't work as it can't find DecodeHintType.
Since it's running client side import/require don't work.

I'm making use of the index.min.js script to run the scanners.

I need the FNC1 group separators to be included in the scan to process the information.

```
   var hints = new Map();
   hints.set(DecodeHintType.ASSUME_GS1, true)

   const codeReader = new ZXing.BrowserMultiFormatReader(hints)
   window.addEventListener('load', scanSetup()) 
```

Thanks in advance for the help.

**Comment by stevesum** [comment]
ZXing.DecodeHintType.ASSUME_GS1

**Comment by shaunwurdeman** [comment]
Ah... so obvious. Thanks very much.
