### ISSUE TITLE
will you add support for CODABAR code?

### ISSUE THREAD

**Issue by dodobelieve** [zxing-js/library#194]
will you add support for CODABAR code?
looking forward to it.

**Comment by odahcam** [comment]
I'm not planning to do that, but PRs are always welcome and I don't know. Maybe in the future if I have some free time I would like to have it here as well.

**Comment by dodobelieve** [comment]
I will try to do it.

**Comment by odahcam** [comment]
Thanks. Also, you can use this issue for tracking your progress and asking for support.

**Comment by dodobelieve** [comment]
> Thanks. Also, you can use this issue for tracking your progress and asking for support.

I've created a PR, but it's blocked by the 'Better Code Hub' check. It gives refactoring candidates for many other source files which i don't change. Any idea?

**Comment by odahcam** [comment]
No worries about that, I'll fix the Better Code Hub issue. I've noticed your PR has no tests, did you finished your coding? If so, I would like to ask you for including the CODABAR unit tests so we can make sure it works now and keeps working along the project. Thanks.

**Comment by dodobelieve** [comment]
ok, i will look into it.
