### ISSUE TITLE
Typescript error in lib

### ISSUE THREAD

**Issue by YouriHugoBos** [zxing-js/library#196]
Since the latest update i am getting the following typescript error: 

**node_modules/@zxing/library/esm5/browser/VideoInputDevice.d.ts(6,22):**
`TS2420: Class 'VideoInputDevice' incorrectly implements interface 'MediaDeviceInfo'.
  Property 'toJSON' is missing in type 'VideoInputDevice' but required in type 'MediaDeviceInfo'.
Version: typescript 3.5.3`

Can anyone help to resolve this error?

**Comment by odahcam** [comment]
I can help, but first, how's it blocking your development?

**Comment by YouriHugoBos** [comment]
Thanks for the response! We have a pipeline setup that fails to build production when there are 'errors' (such as missing required property on type) in the building process.

**Comment by odahcam** [comment]
I just wonder why your tsc is checking for a external source and failing because of it. I remember I had this issue myself once and it wwas a missconfiguration of mine.

**Comment by YouriHugoBos** [comment]
Thanks you so much :), i will check the config. It is indeed a bit strange that it fails of external source.

**Comment by bop10** [comment]
I have the 0.15.1 version, and i still get the error

**Comment by odahcam** [comment]
Sorry, but method is implemented here:

https://github.com/zxing-js/library/blob/be06578976773f901e25b6711d321b72445da5ed/src/browser/VideoInputDevice.ts#L24-L32

Feel free to open a new issue if you feel like you should.

**Comment by bop10** [comment]
Looks like a problem with Angular 8.2 (maybe typescript 3.5?) , i had to downgrade to 8.1.3 and it started to work again

**Comment by iskaron** [comment]
Can confirm, when using typescript 3.5.3, I am getting this error with angular 8.2. Downgrading typescript to 3.4.5 works with angular 8.2.4

**Comment by odahcam** [comment]
Could you post a log or something about it? Or even open a new issue.
