### ISSUE TITLE
Mobile camera recording in black and white

### ISSUE THREAD

**Issue by AlvaroRuizITCL** [zxing-js/library#197]
Hello,

when using an Alcatel 1X mobile I have experienced a very strange issue. The camera is capturing video in black and white. If I use the built-in camera app, the video is in color.

These are the versions I am using:

Android: 8.1.0
Google Chrome Mobile: 75.0.3770.101
zxing-js: 0.14.2

**Comment by lenny76** [comment]
Try Change the device media you are using
I've the same problem with Huawei
