### ISSUE TITLE
It's possible to creat a snapshot from BrowserMultiFormatReader ?

### ISSUE THREAD

**Issue by soltan13** [zxing-js/library#205]
Hi,
Is there a easy way to create a snapshot from BrowserMultiFormatReader ?
Reading code from a webcam is ok, but I need to take an image from the video stream, read the bar/qrcode from this image (with decodeFromImage() ?). And after copy this image on a place, but this is not the point here.

Thank you in advance for your answer and help.

**Comment by odahcam** [comment]
You can try to grab the video frame and draw it to a canvas, exactly the same way the library does to scan it. Also you can use the binary data returned inside the Result object to re-create the original code. We currently have no other methods to do that and there are no APIs available in the library to do that. In the future the stream object could be exposed via a getter method so users can work with it as needed.
