### ISSUE TITLE
NotFoundException while decoding

### ISSUE THREAD

**Issue by graycraft** [zxing-js/library#206]
Trying to decode the image below containing valid QR code throws `NotFoundException`.
![IMG_0775](https://user-images.githubusercontent.com/5364018/62128088-16249400-b2ed-11e9-9261-a3b211f7aae5.JPG)
Chrome 75.0.3770.142:
![Screenshot_2019-07-30_17-07-29](https://user-images.githubusercontent.com/5364018/62128217-626fd400-b2ed-11e9-8066-f472660d270e.png)
Firefox 68.0.1:
![Screenshot_2019-07-30_17-02-40](https://user-images.githubusercontent.com/5364018/62128208-5edc4d00-b2ed-11e9-85b7-60885f524714.png)
Fiddle for reproduce, using @zxing/library@0.15.1: https://jsfiddle.net/graycraft/esmfvohk

**Comment by odahcam** [comment]
I don't think that that base 64 is a valid source and even if it's valid I'm not sure the library can handle that. Also, the QR code can be easily decoded using the ngx-scanner, so I'm sure its not a library error. At the worst of the scenarios it could be an error with the browser layer of the library, but as the [codes in the demo app](https://zxing-js.github.io/library/examples/qr-image/) are fine, I don't think there's any problem with the library itself.

If you still think there's some issue, please provide the source file for debugging.

**Comment by graycraft** [comment]
base64 of the image is valid, URL containing it too.
Library can decode it by [`decodeFromImageUrl(url)`](https://github.com/zxing-js/library/blob/master/src/browser/BrowserCodeReader.ts#L602) or [`decodeFromImage(source, url)`](https://github.com/zxing-js/library/blob/master/src/browser/BrowserCodeReader.ts#L473).
QR code is readable by other tools, that's the issue.
I copied `index.html` you provided and replaced image with one throwing the exception: [https://graycraft.github.io/qr-image-notfoundexception/index.html](https://graycraft.github.io/qr-image-notfoundexception/index.html)
[Source image file](https://graycraft.github.io/qr-image-notfoundexception/IMG_0775.JPG) is above, it is exactly the same as in the fiddle and in the test repository.

**Comment by jescobar-i-strategies** [comment]
did u solve that ?

**Comment by odahcam** [comment]
Nope. I encourage you to give a shot on the new @zxing-js/browser package.

**Comment by mor12** [comment]
im having this issue :C is there any update?

**Comment by odahcam** [comment]
No browser related stuff will be updated in here, please take a look at the @zxing-js/browser repo.

**Comment by mor12** [comment]
if anyone is having this issue i just change of library, try qr-scanner of NIMIQ

**Comment by odahcam** [comment]
Hope it suits you well. I'll say one last time @zxing-js/browser library should be considered by anyone in here.
