### ISSUE TITLE
Set the number of frames to reduce load at  'decodeFromInputVideoDeviceContinuously'

### ISSUE THREAD

**Issue by hwkim94** [zxing-js/library#207]
hello! 
I have a question about  'decodeFromInputVideoDeviceContinuously' in [https://github.com/zxing-js/library/blob/master/src/browser/BrowserCodeReader.ts]

I want to set the number of frames which is checked by 'zxing'.
Because we don't have to check all frames (maybe 40~50 fps).

Is there any way to set the number of frames which is checked by 'zxing' to reduce load? 
I want to show full video (40\~50 fps) but checking only few frames (5\~10fps)

thanks

**Comment by odahcam** [comment]
There's a way to do something like that by configuring a delay between decode attempts in the scanner. But there's no way to set how many frames the scanner will try to decode in one second.

**Comment by hwkim94** [comment]
oh, thanks odahcam!
Then, how can I do delay between decode? Can you explain this way?

**Comment by odahcam** [comment]
Yep, you're welcome. Since you're using the library in the browser, you can do it as simply as `myCodeReader.timeBetweenDecodingAttempts = 1000` (time is in milliseconds) or some other time you want.

**Comment by hwkim94** [comment]
really thanks to your kindness!
