### ISSUE TITLE
QR code scan does not work (js file is missing)

### ISSUE THREAD

**Issue by Jdeboysere** [zxing-js/library#208]
Your QR Code scan does not work...
https://zxing-js.github.io/library/examples/qr-camera/

```
GET https://zxing-js.github.io/library/examples/qr-camera/index.min.js net::ERR_ABORTED 404 at (index):70

Uncaught ReferenceError: ZXing is not defined at (index):119
```

**Comment by odahcam** [comment]
So you are trying to use the script from the example. Do you realize that is an example application, right? It is a working example application with it's own script, for it's own use. It is not a CDN or some provider like that. You want to use it, nice, at least read the README, please. Be my guest to use a working CDN with a script that will fit your needs: https://unpkg.com/@zxing/library@0.15.1/umd/index.min.js

**Comment by Jdeboysere** [comment]
I think you mistunderstood the problem.

I followed yours examples form your website: https://zxing-js.github.io/library/
All yours exemples work online except this one: Scan QR Code from Video Camera (https://zxing-js.github.io/library/examples/qr-camera/).

When I go on your repo, the file /examples/qr-camera/index.min.js seems to be missing. That is the message "GET https://zxing-js.github.io/library/examples/qr-camera/index.min.js net::ERR_ABORTED 404 at (index):70" said.

**Comment by Jdeboysere** [comment]
Thank for closing this problem without solving it and without understand it.

**Comment by odahcam** [comment]
You are very welcome pal.

**Comment by odahcam** [comment]
This is open source, I have no obligation to do anything, so calm down and try get used to it.

**Comment by odahcam** [comment]
You are welcome. I'd just like to remind you that this is open source, I have no obligation to do anything, so calm down and try get used to it.

**Comment by Jdeboysere** [comment]
Thanks you for this fix.
