### ISSUE TITLE
Repeatedly prints the wrong value in console while checking in the example Scan 1D/2D Code from Video Camera

### ISSUE THREAD

**Issue by robinjos333** [zxing-js/library#211]
The example Scan 1D/2D Code from Video Camera, After two or three successful reading the example continuously prints the wrong value in console.
In my case : 
Object { text: "116131397848886", rawBytes: null, numBits: 0, resultPoints: (4) […], format: 12, timestamp: 1566899520096, resultMetadata: null }
multi-camera:95:25

**Comment by robinjos333** [comment]
yes

**Comment by odahcam** [comment]
Could you send a print screen or gif for me to understand what is exactly happening?

**Comment by robinjos333** [comment]
![Screenshot from 2019-09-02 11-44-49](https://user-images.githubusercontent.com/17058045/64093868-7dfc4d80-cd77-11e9-848d-128bc1c81771.png)

**Comment by robinjos333** [comment]
Any updates regarding this issue?

**Comment by odahcam** [comment]
I couldn't reproduce it yet, sorry.

**Comment by robinjos333** [comment]
I am using
Ubuntu 18.04.2 LTS (64-bit)
Firefox Quantum 69.0 (64-bit)
Webcamera - iball C8.0 FACE2ECAF

**Comment by lundal** [comment]
Looks like i have the same issue in a local project. About 10-15 minutes after starting decodeFromStream(), it begins to issue a RSS_14 (format 12) barcode every scan interval, unless i completely black out my camera. Each callback has the same barcode at the same coordinates, but it changes after reloading the page.

![Screenshot from 2019-09-22 13-28-25](https://user-images.githubusercontent.com/1502260/65386543-65ab9d00-dd3d-11e9-9e79-0ab4b9cfabc6.png)

@zxing/library 0.15.1
Chromium 76.0.3809.100
Ubuntu 19.04 (64-bit)
ThinkPad integrated webcam

**Comment by odahcam** [comment]
Occurs only when scanning RSS-14?

**Comment by lundal** [comment]
I'm only purposefully scanning Code 128 and EAN-13 barcodes, but the continuously triggered wrong barcodes are always RSS-14. Seems like the RSS14Reader gets stuck somehow, perhaps by some noise in the video feed that map to unexpected values? I guess i'll just disable RSS-14 decoding in my project to work around it.

**Comment by odahcam** [comment]
It only happens with this specific video?

**Comment by lundal** [comment]
No issues after using hints to only enable Code 128 and EAN-13. All the wrong barcodes i have seen have been RSS-14.

**Comment by odahcam** [comment]
Right, thanks.

**Comment by odahcam** [comment]
ping @odahcam

**Comment by infuzz** [comment]
Hi, I got exactly the same issue ! 
After some successfull qrcode scans, I suddenly got repeatedly a false value coming form nowhere.... 
reset method call do not change anything.
Each line looks like that:

`
{text: "11613051567673",
rawBytes: null,
numBits: 0,
resultPoints: [
0: i {x: 248, y: 255},
1: i {x: 342, y: 255},
2: i {x: 298, y: 180},
3: i {x: 257, y: 180}],
format: 12,
timestamp: 1582672746750}`

**Comment by odahcam** [comment]
Could any of you create a online demo (open source) were the error is showing?

**Comment by vrebo** [comment]
I have the same issue.

The current demo (https://zxing-js.github.io/library/examples/multi-camera/) can be used to trigger the issue.

In my case, it was triggered after move this barcode (https://barcode.tec-it.com/en/Code128?data=0180659777631032653693) in front of the camera in repeated times.

The Reader doesn't log any result when the camera image is in complete black.

**Comment by infinite4evr** [comment]
I have tried to reproduce this issue in this small template html, Used alert coz I don't have debugger on for my android, Scanning bar codes of other types are working fine, but once RSS_14 type bar code is scanned, it continuously sends the same bar code for further scans 
[https://gist.github.com/infinite4evr/fc51a14612550d0506704357586bde16](url)

You can use a temporary html hosting site and paste this html in it.

**Comment by odahcam** [comment]
I see, it seems to be exclusive to RSS 14 decodings. That should make it easier to find the problem.

**Comment by arthurmmedeiros** [comment]
Just wanna say I'm having the same issue with RSS 14. After a few minutes the callback function gets values out of nowhere.

**Comment by neumartin** [comment]
Hi!
Any update with this bug?

**Comment by odahcam** [comment]
No updates yet. RSS 14 needs a review.

**Comment by haykkarapetyan** [comment]
Hi there, 
Is there any update on this? I' have the same issue with decoding RSS_14 barcodes.

**Comment by paulzala** [comment]
I've experienced the same issue after the library is left running for a while - not actually after scaning any RSS_14 barcodes, but just starts firing the callback continuously.
