### ISSUE TITLE
How can I create a bounding box that shows the barcode area while scanning?

### ISSUE THREAD

**Issue by constmoon** [zxing-js/library#216]
I want to create a bounding box that displays 'detecting barcode' on the video screen while scanning. 
Is there any method to create the bounding box? 
If not, I wonder which part should I need to modify. 
Or do you have any plans to support it?

**Comment by odahcam** [comment]
I think you want something like #185, so here we go:

- Nothing implemented.
- No plans (it's complex and I'm too busy/have other priorities).
- About what to modify: you may want to read #185, #39 and override some reader method, anyway you gonna have to draw the box yourself using the read cordinates.
