### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by nathanaelmartin** [zxing-js/library#220]
Hello, 
Your documentation is not up to date, is it possible to have a non deprecated code for integration examples ? 
For example : const codeReader = new BrowserQRCodeReader();
This code is deprecated on your lib, it will be interesting to have the new way to implement your lib :)

**Comment by odahcam** [comment]
The docs are up to date, the deprecation is just as a warning this will be moved to another project in the future. It should already be moved by now, but as this is open and free source, it doesn't, sorry.

PRs are always welcome btw, thanks for reaching out.
