### ISSUE TITLE
4-State Barcode support

### ISSUE THREAD

**Issue by mafster** [zxing-js/library#221]
Is there any developments to supporting 4-state Barcodes? (Royal Mail)

I think these people may support it but its all under license...
https://www.npmjs.com/package/barcode-js

**Comment by odahcam** [comment]
Does not look like an easy solution to use. Anyway, we do not support this type of barcode and do not have any plans to do it. As always, PRs are welcome.

**Comment by mafster** [comment]
I am working on implementing this feature and potentially have a workign algorithm however my dev test iteration is slow because i cant build and test new code quickly. I'm reasonably new to typescript but have worked in javascript before. bit of an  embarrassing question.....how can i test this in a simple example in browser? Or even pass in a sample image...with javascript we could just add a module or script in html for example.

**Comment by odahcam** [comment]
You can use something like `yarn test --watch` in this repo.

**Comment by mafster** [comment]
Keen to get someone's feedback on this branch:
https://github.com/mafster/library/tree/feature/rm4s-reader

I havent put in a pull request as not really sure what the scope is for a "complete" enhancement, as its not done yet, Also never really worked with other opensource projects on github before. It is a little niche in that it focuses primarily on one application of 4-state barcode.

It works fine on all the use case ive needed it for however i havent implemented using the reedSolomon error fixing which i assume would give it. Mainly cos its over my head and havent got much time to look into it. In any case, it's a wip. Succesfully passes all 6 image tests ive added.

**Comment by odahcam** [comment]
Nice job! I just think that if we would add it here, we shouldn't put it into the core, I think a ext folder would be more appropriated, so it would be very welcome.
