### ISSUE TITLE
Please add a description about the scan results

### ISSUE THREAD

**Issue by NieHang** [zxing-js/library#223]
Please add a description about the scan results。
I don't quite understand the resultPoints in the scan results. I hope you can explain them in the documentation.
thank you very much

**Comment by odahcam** [comment]
Quick reference: https://stackoverflow.com/a/31328739/4367683

**Comment by NieHang** [comment]
hi，How to convert resultPoints to pixels？
do you have any good advice? 
thank you very much

**Comment by odahcam** [comment]
You can use something like `yarn test --watch` in this repo.

**Comment by odahcam** [comment]
As long as I know the ResultPoints should be pixels.

**Comment by NieHang** [comment]
> As long as I know the ResultPoints should be pixels.

Ok, I just think the ResultPoints coordinates are a bit outrageous.

I want to scan the QR code in a box, but the resulting ResultPoints coordinates are outside the bounds of this box.I want to scan the QR code in a box, but the resulting ResultPoints coordinates are outside the bounds of this box.

Thank you very much for your help and your open source library.
