### ISSUE TITLE
Image not decoded with datamatrix scanner

### ISSUE THREAD

**Issue by timmawsw** [zxing-js/library#224]
Hey, 
I've been trying to set-up your "Scan QR-code from image" demo ( https://zxing-js.github.io/library/examples/qr-image/ ) with the datamatrix code-reader. What I did was basically just exchanging the line
`const codeReader = new ZXing.BrowserQRCodeReader()` with 
`const codeReader = new ZXing.BrowserDatamatrixCodeReader()`

Unfortunately this turned out to not decode but also not give any error back so I investigated further and found that the DatamatrixCodeReader returns infinite setTimeouts. This is what chrome tells me when the log level is on verbose:

`[Violation] 'setTimeout' handler took 116ms` where the ms-time is different all the time.

I checked the line of code that causes it and it is line 1166 (with auto format the zxing.min.js)
`if (l || c && r) return setTimeout(function () {
              return o(a, i)
            }`

so I compared the values from those variables with the ZXing.BrowserQRCodeReader() and it turns out that for **QR** it is: 

`Var l (false) || var c (false) && var r (true)`

while for **Datamatrix** the variables are: 

`Var l (false) || var c (true) && var r (true)`

I am not sure if this has something to do with the fact that we are trying to decode an image or not. Maybe I need to consider something else when setting up the datamatrix reader? I could not find any documentation for the js-port but at least on the Java-Zxing it states that you should not need any parameters.

**Comment by Trcx528** [comment]
Just wanted to chime in with a "me too." 

Although my findings are a little different.  I'm using the BrowserMultiFormatReader with data matrix.  Data matrix does scan but it is much slower than other formats and in general take a lot of playing to get it to scan. Also I found that larger barcodes read better.

**Comment by odahcam** [comment]
Hey, it shouldn't require any extra parameters for DataMatrix to work, but it maybe does take too much time to decode in the browser.

**Comment by spaceemotion** [comment]
Hey, I also just got this "issue" even though I am using a fairly simple image:
![image](https://user-images.githubusercontent.com/429147/67412810-44e69980-f5c0-11e9-950d-e4396cc4e43f.png)

Here is my test code:
```html
<!DOCTYPE html>
<html>
    <body>
        <img src="image.png" id="img">

        <script type="text/javascript" src="https://unpkg.com/@zxing/library@latest"></script>
        <script type="text/javascript">
          window.addEventListener('load', async () => {
            const codeReader = new ZXing.BrowserDatamatrixCodeReader();
            const img = document.getElementById('img');

            const result = await codeReader.decodeFromImage(img);
            console.log(result);
          });
        </script>
    </body>
</html>
```

(I used `php -S localhost:8080` to run a local server)

**Comment by timmawsw** [comment]
@spaceemotion 

A reason could be that your image is too small. If I use images between 300px - 800px the scanning works. I tried small datamtrixes (from online datamatrix-generator websites) that just have like 50x50 and those were never detected.

Also the workaround with BrowserMultiFormatReader works for me right now.

```javascript
const hints = new Map();
            hints.set(ZXing.DecodeHintType.POSSIBLE_FORMATS, [
                ZXing.BarcodeFormat.DATA_MATRIX
            ]);
            const codeReader = new ZXing.BrowserMultiFormatReader(hints);
            codeReader.decodeFromImage(img).then((result) => {
....
}`

This is the setup I use at the moment and for a workaround it is fair enough. Maybe someone finds the time and deep dives into the issue.

**Comment by spaceemotion** [comment]
Are you referring to the size of the matrix code itself or the actual image it sits in? I chose the datamatrix code over a qr one because it is a lot smaller. Since it will be printed out the image size of the scan will be higher than the one i got here. However, even using the camera didn’t help.
