### ISSUE TITLE
Scanning at 90 degrees rotation

### ISSUE THREAD

**Issue by MrChriZ** [zxing-js/library#226]
Should this work when the barcode is rotated to 90 degrees?

At present in my experiments it's only scanning if the barcode is aligned vertically.
This pull request kind of indicates it should work:
https://github.com/zxing-js/library/pull/101

**Comment by MrChriZ** [comment]
I've got this working:
```
const hints = new Map();   
hints.set(DecodeHintType.TRY_HARDER, true);
let barcodeReader=new BrowserMultiFormatReader(hints);   
barcodeReader.decodeOnceFromConstraints(mediaStreamConstraints, 'video')
....
```
For reasons I don't understand I couldn't get it working with BrowserBarcodeReader

I think something int the documentation about hints would be handy.

**Comment by przemyslawzadomski** [comment]
Hi. I have question, what I need to do to make the camera work after rotate?

**Comment by odahcam** [comment]
`TRY_HARDER` should do the trick. Keep in mind that the most resources you use, the most difficult it gets to successful decode.

**Comment by przemyslawzadomski** [comment]
unfortunately it doesnt work :( maybe i do something wrong...
`
const { DecodeHintType } = require('@zxing/library/esm5')
const hints = new Map();   
hints.set(DecodeHintType.TRY_HARDER, true);
const codeReader = new BrowserMultiFormatReader(hints);
`

`codeReader
            .getVideoInputDevices()
            .then(videoInputDevices => {
                this.setState({
                    videoInputDevices,
                    selected: videoInputDevices[videoInputDevices.length-1].deviceId
                })
            }).then(this.scanCode())`

**Comment by odahcam** [comment]
Could you try with https://zxing-js.github.io/ngx-scanner/ to see if it decodes your code successfully? (you can play with some options there) That will help me see if it's your implementation or the library that is failing.

**Comment by MrChriZ** [comment]
I do wonder if try_harder should be the default setting?

**Comment by przemyslawzadomski** [comment]
I tried this right now, and its same problem. 
its working on first case, but its not on second
![20200124_130457](https://user-images.githubusercontent.com/25490470/73068091-a01f7500-3eaa-11ea-8803-276d7b8dc228.jpg)
![20200124_130528](https://user-images.githubusercontent.com/25490470/73068098-a6155600-3eaa-11ea-8563-500852037752.jpg)

**Comment by odahcam** [comment]
> I do wonder if try_harder should be the default setting?

Nope, it adds too much to the decoding process and can make it unecessarily slower for those who don't need it.

**Comment by przemyslawzadomski** [comment]
Hmm, any idea how can I resolve this problem ?

**Comment by odahcam** [comment]
Try to isolate one of the barcodes and point the camera only at it, barcodes can be very hard to decode sometimes and **any** interference can make it difficult for ya. If it don't work I'll need more time to take a look at it.

**Comment by przemyslawzadomski** [comment]
Ok, I will try do that, but now https://zxing-js.github.io/ngx-scanner/ is not working

**Comment by MrChriZ** [comment]
IMO - Reliability and usability should trump speed in my opinion for
default usage.  When I was looking into this I found that on an old low
powered motorola handset without try_harder the results were next to
useless and unreliable on everyday household barcodes, but with try_harder
the device handled the barcodes well and from multiple angles - even on
that device the decoding process wasn't a problem and performed much like
the full zxing app which I've been using for years.

**Comment by przemyslawzadomski** [comment]
Well, I checked again and unfortunately horizontal scanning does not work

**Comment by przemyslawzadomski** [comment]
Hi! I wrote new sample and its working right now with my implementation! But I have to wait 10 seconds with camera to read barcode... Its very long :( there is the way to reduce waiting times?

**Comment by odahcam** [comment]
What device are you using? This delay may be caused by bad camera quality.

**Comment by przemyslawzadomski** [comment]
Huawei p20 lite
