### ISSUE TITLE
Bad camera Samsung Galaxy S10

### ISSUE THREAD

**Issue by 3645-59** [zxing-js/library#229]
Hi,

On the Samsung Galaxy S10 the default choosen camera is the wide angle camera. But with it, the scans are very difficult.

There is a way to choose an another camera ?

Thanks

**Comment by rafaellyra** [comment]
Yes, you can have a select with all the cameras and select the one you want or switch "automatically" between the cameras.
Use  `.getVideoInputDevices()` to get a list of available cameras and `decodeFromVideoDevice($deviceId, ....` to set the camera you want to read from.
[Here is an example that might guide you better on that.](https://github.com/zxing-js/library/blob/master/docs/examples/multi-camera/index.html#L94)

**Comment by odahcam** [comment]
You can also use the `listVideoInputDevices()` method on [`BrowserCodeReader`](https://github.com/zxing-js/library/blob/master/src/browser/BrowserCodeReader.ts) instances.
