### ISSUE TITLE
remove canplay event in reset()

### ISSUE THREAD

**Issue by sangrae** [zxing-js/library#230]
Hi,
I found small problem in BrowserCodeReader.ts 
~~~~
private _destroyVideoElement(): void {
...
if (typeof this.videoCanPlayListener !== 'undefined') {
      this.videoElement.removeEventListener('loadedmetadata', this.videoCanPlayListener);
}
~~~~
I think 'loadedmetadata' will change to 'canplay'.

Thanks for your work.

**Comment by odahcam** [comment]
Sorry, which version are you talking about?
Also, what's the problem with loadedmetadata?

**Comment by sangrae** [comment]
in BrowserCodeReader.ts
414 : element.addEventListener('canplay', this.videoCanPlayListener);
...
985: this.videoElement.removeEventListener('loadedmetadata', this.videoCanPlayListener);

"videoCanPlayListener" handler added "canplay" but remove from "loadedmetadata".
