### ISSUE TITLE
How do I set the errorCorrectionLevel when generating a qrCode

### ISSUE THREAD

**Issue by SanderElias** [zxing-js/library#231]
For generating qrCodes its quite usual to be able to set the errorCorrectionLevel during the generation.
I peeked into the source, and found no way to pass this as a parameter, while it seems to be used inside the generator

**Comment by odahcam** [comment]
You probably using the Browser QR code generator, right?

**Comment by SanderElias** [comment]
Yes, I want to use the browser version.

**Comment by odahcam** [comment]
Well, you can use both `write` and `writeToDom` methods to pass some hints to the QR Code writer. Something like:

```typescript
const writer = new BrowserQRCodeSvgWriter();
const hints = new Map();
hints.set(EncodeHintType.CHARACTER_SET, "UTF-8"); // example
hints.set(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H); // what you want

const mySvg = writer.write('this is a qr code', 200, 200, hints);
```

That should work.
