### ISSUE TITLE
Dependency no longer maintained

### ISSUE THREAD

**Issue by basslagter** [zxing-js/library#233]
Getting:
warning @zxing/library > text-encoding@0.7.0: no longer maintained

**Comment by odahcam** [comment]
Thanks, if you have any alternatives I'd be happy to hear about it,

**Comment by basslagter** [comment]
Seems like it has been moved to https://www.npmjs.com/package/@sinonjs/text-encoding

**Comment by odahcam** [comment]
Nice, if you want you can open a PR switching from the old to the new version.

**Comment by basslagter** [comment]
Cloned the repo and tried a Yarn install (on Windows). After struggeling with visual studio dev tools, node-gyp, etc I end up with this error: "error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [D:\src\ventrix\library\node_modules\sh
arp\build\sharp.vcxproj". No clue where this is coming from.

**Comment by odahcam** [comment]
Sharp is a lib used in the tests to handle image files. Do you have windows-build-tools for node installed on your machine?

**Comment by basslagter** [comment]
Yes I have. Tried all sorts of things already. Will give it another shot

**Comment by odahcam** [comment]
I was also having strange build-time errors, I fixed it by deleting the project, cloning again and fixing some package versions. You can give a try to the feature/pdf417-reader branch, which has the most updated code to see if it works for ya.

**Comment by odahcam** [comment]
Well, the build errors have been fixed for master and develop, so if you still want to give it a try, be my guest.

**Comment by odahcam** [comment]
Text encoding was removed. :)

**Comment by basslagter** [comment]
Cool. Thanks!
