### ISSUE TITLE
Scanning Multiple Times

### ISSUE THREAD

**Issue by jcuenod** [zxing-js/library#234]
I want to have this kind of process:
1. Show a Scan dialog (with the video element) and scan an EAN_13 barcode
2. End the scanning (I'm calling `.reset()` here)
3. Show the main window with scanned information added
4. User presses "scan" again: GOTO 1

I thought I had it working using `BrowserBarcodeReader` but it seems as though `zxing-js` is only successfully scanning the first barcode. The first barcode does work and the camera turns off. 

When I reopen the scan dialog, this code is executing:

    barcodeReader.decodeOnceFromVideoDevice(selected_device_id, 'video')

but it no longer seems to return barcode data.

**Comment by odahcam** [comment]
I think it may be losting the decoding type hint information. Could you try to set the decoding hint for supported barcodes to EAN_13 again after resetting?

**Comment by jcuenod** [comment]
So I now have a reset function that does this:

    barcodeReader.reset()
    barcodeReader.hints = hints

But it still doesn't successfully scan the second time (to be honest though, I'm not 100% certain that this is how you are supposed to call the setter - `BrowserBarcodeReader` doesn' have a `setHints` method though).

**Comment by odahcam** [comment]
If I remember well, you should set the hints in the constructor, but this should work anyways. Looks like we have a bug.

**Comment by jcuenod** [comment]
I actually was setting the hint in the constructor. Also I only started setting the hint because it was failing to read my barcode the _second_ time (it was working fine without the hinting).

Can I add any info or debugging to help resolve this?

**Comment by odahcam** [comment]
A little demo on StackBlitz for example would be more than enough.

**Comment by jcuenod** [comment]
Sorry, this will come, I just don't have time right now...

**Comment by odahcam** [comment]
No problem, I understand.

**Comment by jcuenod** [comment]
Okay, my bad. So I was trying to manage edge cases in which the scanner did not return actual barcode data and so I had a logical error that was preventing second scans. Sorry about that!
