### ISSUE TITLE
NPM Version

### ISSUE THREAD

**Issue by jcuenod** [zxing-js/library#235]
It appears that the latest version on NPM is ahead of the latest release version here.

**Comment by odahcam** [comment]
You are right, I must forgotten to publish the release notes here.

**Comment by jcuenod** [comment]
Thanks @github-actions but this is curiously still unresolved.

**Comment by odahcam** [comment]
Fixed now.

**Comment by odahcam** [comment]
https://github.com/zxing-js/library/releases/tag/v0.15.2
