### ISSUE TITLE
Scan speed?

### ISSUE THREAD

**Issue by lennycode** [zxing-js/library#237]
Is there a way to control how many times per second it scans?

**Comment by odahcam** [comment]
Yes, there is if you are using the browser layer, it's written here:

https://github.com/zxing-js/library/blob/9599156b311508e63cb1c0933c34c89a2e2b97e1/src/browser/BrowserCodeReader.ts#L53-L70

So you just need to set `timeBetweenDecodingAttempts` in your code reader, like this:

```
const reader = new BrowserQRCodeReader();
reader.timeBetweenDecodingAttempts = 2000;
```

That should be enough.
