### ISSUE TITLE
How to pause and un-pause the scan in webpage

### ISSUE THREAD

**Issue by cloudzedge** [zxing-js/library#238]
I am complete noob! I am trying to pause and un-pause the scan in my website.

```
window.addEventListener('load', function () {
              let selectedDeviceId;
              const codeReader = new ZXing.BrowserMultiFormatReader()
              console.log('ZXing code reader initialized')
              codeReader.getVideoInputDevices()
                  .then((videoInputDevices) => {
                      const sourceSelect = document.getElementById('sourceSelect')
                      selectedDeviceId = videoInputDevices[0].deviceId
                      console.log(selectedDeviceId)
                      document.getElementById('qr-code-scan').addEventListener('click', () => {
                          codeReader.decodeFromVideoDevice(selectedDeviceId, 'video', (result, err) => {
                              if (result) {
                                  console.log(result)
                                  //document.getElementById('result').textContent = result.text
                                  window.location.href = result
                              }
                              if (err && !(err instanceof ZXing.NotFoundException)) {
                                  console.error(err)
                                  document.getElementById('result').textContent = err
                              }
                          })
                      })
                      document.getElementById('close-scan').addEventListener('click', () => {
                          //What do i do here?
                      })
                  })
                  .catch((err) => {
                      //console.error(err)
                  })
          })
```

This is what I have. how can i make it pause the scan when i click a button?

**Comment by fiatjaf** [comment]
Did you ever solve this? People want to know!

**Comment by odahcam** [comment]
You can pause the video trough the video tag DOM APIs or use the method `reset()` in your browser code reader to completely stop the scanner.

**Comment by fiatjaf** [comment]
I also just discovered you can use `.decodeOnceFromVideoDevice` and that returns a Promise with the result.

**Comment by BaadalAdam** [comment]
We ended up not using this for the project as it the client dropped the idea, thank you for your help

**Comment by natoszme** [comment]
Hi everyone! I'm reopening this issue since I'm having the same case here.

As @odahcam mentioned, I tried using the `video`'s API but I'm getting the callback called twice in some cases since it seems to be a little difference in the streams used by the library and the camera's: the camera has a newer image without the code, but the callback is called again.

I cannot use `reset` since the video element would go blank for a second and it'd be strange for the final user (that should be able to keep scanning codes after pausing).

Thanks!
