### ISSUE TITLE
Inverted colors code

### ISSUE THREAD

**Issue by jerome-simplyphp** [zxing-js/library#245]
Hi

I implemented Zxing-js library in my project and it works well.
However, I need to be able to decode inverted colors DataMatrix codes.
I found resources like this one which seem to say that it's possible, in theory :+1: https://stackoverflow.com/questions/41112666/scan-with-color-invert-qr-code-doesnt-work-well-in-android-with-zxing

I was wondering is there is already an option available for that, and if not, what would be the proper solution ?

Thanks

**Comment by odahcam** [comment]
Did you take a look on #135 ?

**Comment by jerome-simplyphp** [comment]
Hi
Yes, I found that topic after.
I'll try that.
Thanks

**Comment by odahcam** [comment]
You are welcome, good luck.

**Comment by jerome-simplyphp** [comment]
Hi
Quick update to say it worked.
I didn't test with small DataMatrix yet, thuogh.

Thanks

**Comment by odahcam** [comment]
Nice to read that! I'll be closing this now.
