### ISSUE TITLE
Calling reset after decodeFromInputVideoDevice triggers an error

### ISSUE THREAD

**Issue by MastroLindus** [zxing-js/library#247]
I recently updated my dependency to 0.15.2 and I noticed a behaviour that I am not sure if it is a bug or not.

After I start the scanning process using BrowserQRCodeReader,decodeFromInputVideoDevice, if I interrupt it with reset(), the API generates an exception with message "Video stream has ended before any code could be detected."

Is it a bug? 
If it is not a bug, what is the proper way to stop scanning once started, if I want to allow a user to be able to do so?

So far I am working around this by checking if the error message is exactly ""Video stream has ended before any code could be detected." (there's no error name or other more reliable parameter to sue) and if that's the case, I ignore it, but I don't really like the approach (and it will break any moment you change the message)

Thank you!

**Comment by odahcam** [comment]
Very well noted, you could check for the type of the exception, which is `NotFoundException` instead of the message. In that case I think rejecting the `Promise` (which raises an exception` is the right thing to do. However I'm open to discussion.

**Comment by MastroLindus** [comment]
I am not a fan of the approach, as other errors of type NotFoundException could eventually be added and I might want to treat them differently.
As the original post asks, I think there should be a better way to stop the scan operation  once started without generating exceptions, as it is a common scenario/use case.
I wouldn't mind to have a separate api function to call instead of reset(), if that's not feasible.

**Comment by odahcam** [comment]
There's not good alternative until now. PRs are still welcome.

**Comment by iusegithub** [comment]
Looks like nothing changed on this. Noting that I agree with @MastroLindus point, "I think there should be a better way to stop the scan operation once started without generating exceptions, as it is a common scenario/use case."
