### ISSUE TITLE
Camera device does not work with Ipad or S10 when html page is published on local httpserver.

### ISSUE THREAD

**Issue by lszlp76** [zxing-js/library#248]
When I copy the HTML code from this site (https://zxing-js.github.io/library/examples/multi-camera) and run it locally, it works very well in chrome or another web browser.
Likewise, the camera is activated when I connect to the same page via Ipad or S10.
However, the same codes do not work when sharing over the http server on the local network to test how it looks on your Ipad or any connected android device. Camera is not activated.
The question is, why do these html codes work well online on the Ipad or S10 Galaxy, but not on devices connected to the local network?
Any ideas ??
I'm using httpster for local http server

**Comment by wyred** [comment]
You will need to serve the html page over https. Browsers do not allow webpages to access the camera over non-https connections.

**Comment by lszlp76** [comment]
Thanks a lot! It's worked when it has been deployed over https

**Comment by lszlp76** [comment]
> You will need to serve the html page over https. Browsers do not allow webpages to access the camera over non-https connections.


Thanks! It's worked över https
