### ISSUE TITLE
How to get the highest pixel camera？

### ISSUE THREAD

**Issue by NieHang** [zxing-js/library#250]
hello，I want to know how to get the deviceId of the highest pixel,I can't tell which deviceId has the highest pixel count in videoInputDevices.so I hope you can help me, thank you very much!

**Comment by NieHang** [comment]
![image](https://user-images.githubusercontent.com/27391848/70599290-bf7a7f80-1c27-11ea-90d5-039c6470bedc.png)
If you can add an option to change this variable it will also work

**Comment by odahcam** [comment]
Yep, that's a shame, sorry. But you can always extend the class and overide the function. Consider this as a good workaround.

**Comment by NieHang** [comment]
thank you every much for your help
