### ISSUE TITLE
Camera Defaulting Not Working

### ISSUE THREAD

**Issue by rigiddesign** [zxing-js/library#251]
As per the documentation , it appears I should be able to do the following to allow the class to default to the main back camera:

		var CodeReader = new ZXing.BrowserBarcodeReader();

		CodeReader.decodeFromInputVideoDevice(undefined,'LivestreamScanner').then(function(Result) {
		  // Success
		});

However, I simply get **DOMException: Could not start video source** unless I explicitly define a device ID:

		var CodeReader = new ZXing.BrowserBarcodeReader();

		CodeReader.getVideoInputDevices().then(function(Devices) {
			CodeReader.decodeFromInputVideoDevice(Deveices[0].deviceId,'LivestreamScanner').then(function(Result) {
				// Success
			});
		})

I wouldn't have a problem doing this, however most of the time there's no way of knowing which device is the back one. sometimes the label helps here, but most of the time not :-( Why is it not working as per the documentation? I must've missed something

**Comment by odahcam** [comment]
This may be a bug. Also, the library doesn't really knows what is the "back camera", all it does is request the environment facing camera and the OS returns the camera it wants.

**Comment by rigiddesign** [comment]
> This may be a bug. Also, the library doesn't really knows what is the "back camera", all it does is request the environment facing camera and the OS returns the camera it wants.

Thanks for the update. Yes, it seems the request using the { facingMode:"environment" } property is what's failing. I'll keep an eye on the issue to see if there's an update. Have a good one buddy.

**Comment by odahcam** [comment]
Could you set up a demo for the issue for me to take a look on?

**Comment by rigiddesign** [comment]
> Could you set up a demo for the issue for me to take a look on?

Thanks very much for investigating :-) See: https://temp.rigid.design

      js_zxing.js:4 Uncaught (in promise) s: element with id 'LivestreamScanner' not found

**Comment by odahcam** [comment]
Is there a was to access its code or any source-map?

**Comment by odahcam** [comment]
Are you using a local server to run the code or just opening the HTML?

**Comment by rigiddesign** [comment]
Live on a domain

**Comment by odahcam** [comment]
I fixed it for ya: [Source.zip](https://github.com/zxing-js/library/files/4082049/Source.zip)

**Comment by rigiddesign** [comment]
Thanks. Looking at the files though, you appear to have just done exactly what I did in my above example. The issue was that using undefined as the first argument of  the "decodeFromInputVideoDevice" method doesn't work as documented. Using the first device ID returned in the devices array isn't always guaranteed to be the back facing camera.

**Comment by odahcam** [comment]
You are welcome. In fact, the problem was you forgot to create the video element to receive the camera feed, so I just created that. I probably left some specific device as parameter as I was testing with my front camera.

**Comment by rigiddesign** [comment]
Ah OK, so it appears the demo I setup as an example didn't quite reflect the issue. I quickly knocked up that source so failed to demonstrate the issue correctly.

The correct error that's received when passing undefined is:

      DOMException: Could not start video source

Remove the reference to the device ID you included and you will get the error (error actually doesn't occur when working local, only on a live server)

**Comment by sawrubgupta** [comment]
Sourcecode zip is not working on live
