### ISSUE TITLE
BrowserMultiFormatReader is not working?

### ISSUE THREAD

**Issue by LittleToky** [zxing-js/library#252]
Hi, I need to recognise data matrix image
![Screenshot 2019-12-11 at 12 00 08](https://user-images.githubusercontent.com/15971235/70707797-147eca00-1cea-11ea-9a08-a99c5e56e74c.png)

and i still didn't find way to do this. I've tried to recognise locally your image from example https://zxing-js.github.io/library/examples/multi-image/
using codeReader = new ZXing.BrowserQRCodeReader() and it gave me the code, BUT if I do the same thing with codeReader = new ZXing.BrowserMultiFormatReader() I only get an error 
TypeError: Cannot read property 'complete' of undefined
    at f.p.isImageLoaded (BrowserCodeReader.ts:690)
    at f.p.decodeFromImageElement (BrowserCodeReader.ts:549)
    at f.p.decodeFromImage (BrowserCodeReader.ts:483)

I get the same mistake trying to recognise my image.
P.s. I've seen another issue about data matrix recognition is not working. Is there any demo with data matrixes or it's not working yet?

Thank you!

**Comment by AnthonySpault** [comment]
I have an error too

`Cannot set property 'reader' of undefined`

Data matrixes work on this demo https://zxing-js.github.io/library/examples/multi-camera/

**Comment by odahcam** [comment]
DataMatrix does works. It seems like you have an error on your code, but I'm not sure at all. Could you share a StackBlitz demo of the issue or semthing for us to investigate?

**Comment by AnthonySpault** [comment]
On my side, it works sometimes. It can decode quickly, but sometimes it's very long
any idea of what i can possibly do to improve that ?

**Comment by odahcam** [comment]
Illumination and focus are the main issues when decoding image streams. You could check on these topics and search for a way to better control that in your environment and, if possible, in your device.
