### ISSUE TITLE
different camera angle

### ISSUE THREAD

**Issue by dartess** [zxing-js/library#253]
Hi!

Your library is excellent!

But I have a question, is it possible to enable recognition at an arbitrary position of the barcode in the frame? Is there such an opportunity now or can it be added later?

https://i.gyazo.com/d2a0f8d62a9ec4702e15e6d7c663d458.png

**Comment by odahcam** [comment]
I think this may be a starting point for ya: https://github.com/zxing-js/library/issues/39

**Comment by dartess** [comment]
I'm not sure.

In the case when we want to recognize the barcode on a part of the image, we can ask the user to place the barcode exactly in the desired area.

I have a completely different question. What if we cannot ask to place the barcode exactly in the right area? Some users have difficulty with this (carelessness, rush, physical disabilities). I would like to be able to automatically rotate the image in the pointers of areas similar to barcodes before recognizing them. As I understand it, now there is no such possibility. It seems that this feature will greatly reduce the recognition speed.

**Comment by odahcam** [comment]
>  What if we cannot ask to place the barcode exactly in the right area
In fact there is such functionality and it can do even more attempts with the `tryHarder` hint enabled.

> In the case when we want to recognize the barcode on a part of the image, we can ask the user to place the barcode exactly in the desired area.
I understood that you wanna do the same thing as this comment shows: https://github.com/zxing-js/library/issues/39#issuecomment-392671176 . Did I understand something wrong?
