### ISSUE TITLE
QR camera example

### ISSUE THREAD

**Issue by lajollalerner** [zxing-js/library#257]
when I run on my local machine it works fine, but when I post it to my web server (with external access) i get browser errors [Can't enumerate devices, method not supported.] it can't see the camera. are there other library files or drivers needed on the Web server side besides index.html ?

thank you for your help.

**Comment by avisser** [comment]
Chrome won't access the camera on an unsecure site. Can confirm your site has SSL?

**Comment by lajollalerner** [comment]
That was it! Thank you!

**Comment by odahcam** [comment]
Thanks guys. As you notice I'm unable to keep the house clean by myself. Your help is fundamental.

**Comment by odahcam** [comment]
Also, this is at least related to or duplicate of: #225, #186, #183, #192, #15.
