### ISSUE TITLE
Use decodeFromImage method cause memory usage increasing.

### ISSUE THREAD

**Issue by ReginaLiang** [zxing-js/library#258]
Usage on webapps:
```
const codeReader = new BrowserQRCodeReader();
const promise = codeReader.decodeFromImage(undefined, URL.createObjectURL(imageDataURL));
```
Every time call this decodeFromImage method, the browser memory usage will inscrease about 50MB, every time is up to peak, it's terrible. and free memory is slow, after 3 minutes, the memory will be free. 

Please confirm this issue.
Thanks.

**Comment by odahcam** [comment]
Have you ever seen anything [about this](https://stackoverflow.com/questions/25698581/url-createobjecturl-causes-memory-leak)?

**Comment by ReginaLiang** [comment]
Hi, @odahcam , 
I've tried just use URL.createObjectURL(imageDataURL) and don't call decodeFromImage ,then memory usage won't be inscrease, Only call decodeFromImage(), the memory usage will increase sharply, so i think URL.createObjectURL(imageDataURL) have no effect on memery usage. 
Thanks.

**Comment by ReginaLiang** [comment]
> Have you ever seen anything [about this](https://stackoverflow.com/questions/25698581/url-createobjecturl-causes-memory-leak)?

Hi, @odahcam ,
I've tried just use URL.createObjectURL(imageDataURL) and don't call decodeFromImage ,then memory usage won't be inscrease, Only call decodeFromImage(), the memory usage will increase sharply, so i think URL.createObjectURL(imageDataURL) have no effect on memery usage.
Thanks.

**Comment by magnetnation** [comment]
I have similar issue with BrowserMultiFormatReader and decodeOnceFromVideoDevice.

```
this.reader = new BrowserMultiFormatReader();
const res = await this.reader.decodeOnceFromVideoDevice(this.deviceId, this.video);
```

The memory usage in mobile chrome on android is growing rapidly and leads to page reload with out of memory message.

**Comment by odahcam** [comment]
That's fun. I do expect the memory usage to increase as this proccess is a lot for JS running in browser's engine, but it should not bloat the system. I never noticed this, so I'll keep this open until we confirm that it does not exists in new versions or solve the problem.
