### ISSUE TITLE
same file recognized on online demo but not with js library

### ISSUE THREAD

**Issue by Fr4nZ82** [zxing-js/library#259]
I'm trying to read the barcodes present in some files scanned using nodejs; if I crop the barcode manually and try to read i get the result successfully, if instead I pass the whole scanned page the library cannot find the barcode.

The same file tested with the online demo (https://zxing.org/w/decode.jspx) works.

I leave the links to the whole file and the cropped one:

https://filebin.ca/5BAtMzltwUrC/test.jpg
https://filebin.ca/5BAvhrf0BNNa/test_easy.jpg

and my code: 
https://pastebin.com/5aGeuCda

**Comment by odahcam** [comment]
Sorry, this is not our demo. The link you pasted here is from the original Zing library.
