### ISSUE TITLE
result return "format" index and not string

### ISSUE THREAD

**Issue by lenny76** [zxing-js/library#260]
result format data should be the string of type of barcode and not the index

barcode CODE128
text: "123.456789"
rawBytes: Uint8Array(20) [105, 12, 100, 19, 14, 99, 45, 67, 89, 7, 106, 0, 0, 0, 0, 0, 0, 0, 0, 0]
numBits: 0
resultPoints: (2) [i, i]
**format: 4**
timestamp: 1581342070804
resultMetadata: null

**Comment by akd3vs** [comment]
I did a function to get the name like this:

```javascript
import { BarcodeFormat } from '@zxing/library';
const getFormat = value => Object.keys(BarcodeFormat).find(key => BarcodeFormat[key] === value);

**Comment by odahcam** [comment]
It would be nice to have this function in the lib.
