### ISSUE TITLE
Some QR codes can not recognized

### ISSUE THREAD

**Issue by f5cs** [zxing-js/library#261]
Some QR codes can't be recognized with this library, 
but  can recognized  in https://zxing.org/w/decode.jspx.
What is the difference between the two algorithms? Is the algorithm not synchronized?

**Comment by f5cs** [comment]
the implements of  https://zxing.org/w/decode.jspx  usesed ihttps://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/qrcode/detector/FinderPatternFinder.java.
Andras Toth
The developer Andras Toth developed a JS codes for these implementations.
https://github.com/andrastoth/webcodecamjs/blob/master/js/qrcodelib.js
But he hasn't synced for three years. Some of his algorithms are out of date，
I haven't studied this area. I can't figure out how to improve it for a while. Maybe you can refer to it?

**Comment by crossworth** [comment]
Hi, I know its been a long time, but could you provide the qrcode that cant be recognized with this library?

**Comment by odahcam** [comment]
This project is a full port from Java ZXing to TypeScript, it's basically rewritten in another language, so they will never behave 100% the same. If you want, we could help investigating why that code wouldn't decode with this lib but only with Java version. Feel free to open a new issue.
