### ISSUE TITLE
Impossible to scan a second barcode, after the first has been successfully scanned

### ISSUE THREAD

**Issue by josephernest** [zxing-js/library#262]
I use this:
```
var codeReader;
window.addEventListener('load', () => {
    var audio = new Audio('1417.mp3');
    codeReader = new ZXing.BrowserBarcodeReader();
    codeReader
        .decodeFromInputVideoDevice(undefined, 'video')
        .then((result) => { 
            document.getElementById('results').textContent = result.text;
            audio.play();            
         })
        .catch(err => console.error(err));
});
```

After one successful scan, it's like the BarcodeReader is disabled: I cannot scan another barcode anymore.

**How to enable it for multiple consecutive scans?**

**Comment by odahcam** [comment]
Use `decodeFromInputVideoDeviceContinuously` instead of `decodeFromInputVideoDevice`.

**Comment by josephernest** [comment]
Thanks @odahcam ! By the way, how to temporarily stop the video stream (stopping the "Webcam is filming" LED on some laptops), and pause the barcode reader? And then how to make it start again?

**Comment by odahcam** [comment]
You're welcome. For that you can call the `reset` method and then call the `decodeFromInputVideoDeviceContinuously` again.

**Comment by josephernest** [comment]
Thank you @odahcam !
