### ISSUE TITLE
How I take the result?

### ISSUE THREAD

**Issue by Fernyan** [zxing-js/library#266]
Can someone show me how can I take the result of the scan? I tried to find examples and read the wiki but I don't found

**Comment by odahcam** [comment]
The result comes in the callback:

```TS
codeReader
        .decodeFromInputVideoDevice(undefined, 'video')
        .then((result) => { console.log(result.text); });
```

The `decodeFromInputVideoDevice` just returns a `Promise` which you can await to get the result syncronously:

```TS
const result = codeReader.decodeFromInputVideoDevice(undefined, 'video')
```

You can also run continuous decode from a video input device with [`decodeFromInputVideoDeviceContinuously`](https://github.com/zxing-js/library/blob/a4bafeabf8a10524bca28a9e95ef57e25e3993c8/src/browser/BrowserCodeReader.ts#L311):

```
codeReader
        .decodeFromInputVideoDeviceContinuously(undefined, 'video', result => { /* do something with the result in here /* })
```
