### ISSUE TITLE
Can't enumerate devices, method not supported.

### ISSUE THREAD

**Issue by qq635030106** [zxing-js/library#270]
Please help to solve it

**Comment by slokhorst** [comment]
Please give some details: browser, operating system, hardware, library version.

**Comment by DustinYTY** [comment]
Have the same problem recently with  Safari  in ISO  

hardware: Iphone SE

library version:
https://unpkg.com/@zxing/library@latest

**Comment by duartels** [comment]
Have the same problem with Chrome on Android

**Comment by odahcam** [comment]
Please report decent data for debugging. I'm starting to close issues without data.

@DustinYTY, just use the previous version from v0.16.0 (v0.15.something), that should work for **you**.

**Comment by DustinYTY** [comment]
> Please report decent data for debugging. I'm starting to close issues without data.
> 
> @DustinYTY, just use the previous version from v0.16.0 (v0.15.something), that should work for **you**.

already did so, thank you

> Please report decent data for debugging. I'm starting to close issues without data.
> 
> @DustinYTY, just use the previous version from v0.16.0 (v0.15.something), that should work for **you**.

Already did so , thank  you
