### ISSUE TITLE
How to get the scanned image after the decode is successful ? 

### ISSUE THREAD

**Issue by infinite4evr** [zxing-js/library#272]
I did not find enough info about this online, Would be great if someone could help.

**Comment by odahcam** [comment]
You mean get the image from the moment the library did decode something in a camera feed?

**Comment by infinite4evr** [comment]
Yes

**Comment by Sudhanshu-Cedcoss** [comment]
@odahcam , Any help? Tyia. A great library btw :)

**Comment by infinite4evr** [comment]
@odahcam , Any help? Tyia,  A great library btw :). You can send me an example link? or just let me know the procedure if any, I'll try it.

**Comment by odahcam** [comment]
Sorry I did not had time to work on that for ya, last few day have been crazy. I believe it's possible to create some image from the Result object you get from successful decode results, there's lots of info there.
