### ISSUE TITLE
Does it work on iphone with IOS 13?

### ISSUE THREAD

**Issue by enviloop** [zxing-js/library#273]
Do this library work on iphone with IOS 13?

I tried it on the [DEMO/Live example](https://zxing-js.github.io/library/examples/multi-camera/) but it seems not to get access to the camera. Tested in both Safari and Chrome for iphone.

The version of IOS on the iphone is (13.3.1)

**Comment by odahcam** [comment]
Yes, but this docs kinda still poor. Please refer for this link for testing: https://zxing-js.github.io/ngx-scanner/

It's just an Angular app that wraps this library.

**Comment by arashetm** [comment]
That link works perfect on iPhone with Safari,
But what about chrome? still not working because of the security permission error!

**Comment by odahcam** [comment]
@arashetm #149
