### ISSUE TITLE
PDF417Reader throws image.getBlackMatrix is not a function.

### ISSUE THREAD

**Issue by KeanuJooste** [zxing-js/library#275]
Good day,

I am trying to decode a pdf417 with angular using your library (PDF417Reader) for some reason i get the following error: TypeError: image.getBlackMatrix is not a function. I also got issues about int and float usiage in several files. Is there anyway someone can maybe help me about actually decoding pdf417? Any help is appreciated.

**Comment by odahcam** [comment]
Please send example.;

**Comment by KeanuJooste** [comment]
ERROR TypeError: image.getBlackMatrix is not a function
    at Function.push../node_modules/@zxing/library/esm5/core/pdf417/detector/Detector.js.Detector.detectMultiple (Detector.js:63)
    at Function.push../node_modules/@zxing/library/esm5/core/pdf417/PDF417Reader.js.PDF417Reader.decode (PDF417Reader.js:110)
    at PDF417Reader.push../node_modules/@zxing/library/esm5/core/pdf417/PDF417Reader.js.PDF417Reader.decode (PDF417Reader.js:72)
    at AppComponent.capture (app.component.ts:60)
    at Object.eval [as handleEvent] (AppComponent.html:7)
    at handleEvent (core.js:43993)
    at callWithDebugContext (core.js:45632)
    at Object.debugHandleEvent [as handleEvent] (core.js:45247)
    at dispatchEvent (core.js:29804)
    at core.js:42925

**Comment by KeanuJooste** [comment]
node_modules/@zxing/library/esm5/core/ResultPoint.d.ts:10:20 - error TS2304: Cannot find name 'float'.

10     constructor(x: float, y: float);
                      ~~~~~
node_modules/@zxing/library/esm5/core/ResultPoint.d.ts:10:30 - error TS2304: Cannot find name 'float'.

10     constructor(x: float, y: float);
                                ~~~~~
node_modules/@zxing/library/esm5/core/ResultPoint.d.ts:11:13 - error TS2304: Cannot find name 'float'.

11     getX(): float;
               ~~~~~
node_modules/@zxing/library/esm5/core/ResultPoint.d.ts:12:13 - error TS2304: Cannot find name 'float'.

12     getY(): float;
               ~~~~~
node_modules/@zxing/library/esm5/core/ResultPoint.d.ts:14:17 - error TS2304: Cannot find name 'int'.

14     hashCode(): int;
                   ~~~
node_modules/@zxing/library/esm5/core/ResultPoint.d.ts:28:68 - error TS2304: Cannot find name 'float'.

28     static distance(pattern1: ResultPoint, pattern2: ResultPoint): float;
                                                                      ~~~~~
node_modules/@zxing/library/esm5/core/common/BitMatrix.d.ts:137:17 - error TS2304: Cannot find name 'int'.

137     hashCode(): int;

**Comment by spazjr01** [comment]
I am also getting these same errors after installing the library to my solution and adding code, and then rebuilding
[Build errors after installing zxing-library.docx](https://github.com/zxing-js/library/files/4331888/Build.errors.after.installing.zxing-library.docx)
:

const codeReader = new BrowserPDF417Reader();
            codeReader
                .decodeFromImage(undefined, this._canvasElement.toDataURL())
                .then(result => console.log(result.getText()))
                .catch(error => console.log(error)); establishing a , and then building.

Any answers to this problem?

**Comment by jankaderabek** [comment]
Hi, is there any update? I have the same issue. I think it is the same issue as in https://github.com/zxing-js/library/issues/278 But I didn`t find any reasonable solution how to fix this problem.

```
 ERROR  ERROR in /Users/jankaderabek/Pecka/nay-tool/node_modules/@zxing/library/esm/core/common/BitMatrix.d.ts(137,17):                                nuxt:typescript 14:31:21
137:17 Cannot find name 'int'.
    135 |     getRowSize(): number;
    136 |     equals(o: Object): boolean;
  > 137 |     hashCode(): int;
        |                 ^
    138 |     /**
    139 |      * @return string representation using "X" for set and " " for unset bits
    140 |      */


 ERROR  ERROR in /Users/jankaderabek/Pecka/nay-tool/node_modules/@zxing/library/esm/core/common/StringUtils.d.ts(40,54):                               nuxt:typescript 14:31:21
40:54 Cannot find name 'int'.
    38 |      * Returns the charcode at the specified index or at index zero.
    39 |      */
  > 40 |     static getCharCode(str: string, index?: number): int;
       |                                                      ^
    41 | }
    42 | 

```

**Comment by odahcam** [comment]
Please guys, test the new v0.16.3 release and let me know if this issue persists. Thanks.

**Comment by jankaderabek** [comment]
@odahcam I have tried the version v0.16.3 and everything work fine 👍 Thank you for fix
