### ISSUE TITLE
Samsung devices couldn't use decodeFromImage function

### ISSUE THREAD

**Issue by chunjay95** [zxing-js/library#276]
Hi all, I am still new to writing up a new issue in github. So if there is anything wrong with the format I would like to apologize first.

So, I am currently using ionic 4 and implementing scan from gallery function. 
I noticed that when I use any Samsung devices it will always fail with just an error message of Q. I do not know why as I tested the library with Huawei and Xiao Mi devices and both of these devices works just fine. 

The code that I am using is as follows: 

```
this.browserQrCodeReader.decodeFromImage(img2).then((x) => {
        console.log("yay::: " + JSON.stringify(x.getText()));
      }).catch((err) => {
        console.log("nos:::" + err.toString());
        console.log("nos message:::" + err.message);
        console.log("nos stack:::" + err.stack);
        console.log("nos get own property names:::" + JSON.stringify(err, Object.getOwnPropertyNames(err)));
        console.log("nos delete error:::" + delete err._zone_symblo_currentTask);
      });
```

The error stack trace is as follows: 

`Line 1 : nos stack:::Q
03-11 12:30:16.417 20294 20294 D SystemWebChromeClient:     at Function.checkAndNudgePoints (http://localhost/build/vendor.js:1:819160)
03-11 12:30:16.417 20294 20294 D SystemWebChromeClient:     at Object.sampleGridWithTransform (http://localhost/build/vendor.js:1:821934)
03-11 12:30:16.417 20294 20294 D SystemWebChromeClient:     at Function.sampleGrid (http://localhost/build/vendor.js:1:832125)
03-11 12:30:16.417 20294 20294 D SystemWebChromeClient:     at vA.processFinderPatternInfo (http://localhost/build/vendor.js:1:831704)
03-11 12:30:16.417 20294 20294 D SystemWebChromeClient:     at vA.detect (http://localhost/build/vendor.js:1:831028)
03-11 12:30:16.417 20294 20294 D SystemWebChromeClient:     at QA.decode (http://localhost/build/vendor.js:1:834342)
03-11 12:30:16.417 20294 20294 D SystemWebChromeClient:     at t.a.decodeBitmap (http://localhost/build/vendor.js:1:782068)
03-11 12:30:16.417 20294 20294 D SystemWebChromeClient:     at t.a.decode (http://localhost/build/vendor.js:1:781518)
03-11 12:30:16.417 20294 20294 D SystemWebChromeClient:     at n (http://localhost/build/vendor.js:1:780924)
03-11 12:30:16.417 20294 20294 D SystemWebChromeClient:     at http://localhost/build/vendor.js:1:781103
`

May I know how should I proceed from here?

*** EDIT ***
Found out that if I generate a QR that has smaller content Samsung devices are able to detect the QR. 
Is it possible that big content QR cant be decoded??

**Comment by odahcam** [comment]
Could it be a problem with the device itself or with the ionic layer where the device can't support big image conversion?

**Comment by chunjay95** [comment]
Hi @odahcam. First of all i want to thank you so much for this library. Been searching everywhere for something like this.

Secondly, I dont think it is the problem itself. I used s10 Lite and s20 Ultra to test the library on scan from gallery. Quite odd that some QR it couldnt scan and some it can. 

I thought it was the image size that it couldnt decode as well. but turns out it wasnt. Cause i did take new screenshots of some qr and it did work. It is really odd.

I really dont know how to explain it. The images I used for all the devices are the same but Samsung devices couldnt detect the image for some reason. 

May I know what is the error message Q is for?

**Comment by odahcam** [comment]
Thanks @chunjay95. I have no ideia what is that error too. Do you have any print pf the stack trace or anything like that for me to analyze?

**Comment by chunjay95** [comment]
@odahcam I don't really have anything else other than that error message. That is why it is hard for me to figure out where is wrong as well. It is really weird though. Just that one particular image it couldnt scan. 

Any other pictures that i now started taking it is able to decode @.@

**Comment by chunjay95** [comment]
Hi all, just found out that it is a little buggy with Samsung devices where some of the images it can decode and some it couldnt. Sorry

**Comment by odahcam** [comment]
That's kinda sad, I hope we can do better in the future.
