### ISSUE TITLE
Doesnt recognize big data matrix

### ISSUE THREAD

**Issue by RudiX** [zxing-js/library#277]
Hi,
i haven an issue with the lib. it works nice on small a small datamatrix (4x4 fields), but doesnt recognize  for exmple the attached data matrix. tested with demo as scan-from-video and scan-from-image with and without hints and alternating DataMatrrixReader and MultiFormatReader
![04](https://user-images.githubusercontent.com/1477781/76391109-a4262a00-6366-11ea-8039-3c23374b4159.png)

**Comment by odahcam** [comment]
I tried to decode this here vie browser, but it just took forever and never decoded. Can you share some error at least?

**Comment by RudiX** [comment]
I donr recieve an error either. However this is a valid data matrix code, which can be decoded by other apps

**Comment by odahcam** [comment]
I would say we had a memory limit reach or something, but I could decode this with the Angular scanner component, so it must be an error with something else, maybe the browser layer (it has a history of being a bit unstable). 

Decoded result:
![image](https://user-images.githubusercontent.com/3942006/81087523-3878bd00-8ed0-11ea-86ce-e1730567cf4f.png)
