### ISSUE TITLE
cannot read property 'getCodewords' of null

### ISSUE THREAD

**Issue by Lux589** [zxing-js/library#280]
I get the above error when using BrowserPDF417Reader.decodeFromVideoDevice.

**Comment by Lux589** [comment]
Manage to sort it out. Realized that when scanning, the phones orientation show be the same as the orientation of the barcode if its a bit skewed it throws the above error but if its inline it decodes the correct data from the barcode. closing

**Comment by odahcam** [comment]
Hey, this is really a bug and that Exception should not occour, we will follow up on #318. Thanks for sharing.
