### ISSUE TITLE
issue on multi-camera when using offline

### ISSUE THREAD

**Issue by sakibyousuf** [zxing-js/library#284]
HI
when i browse " https://zxing-js.github.io/library/examples/multi-camera/" online it works fine on my android device browser. 
but when i save the source code and run it on desktop it again works  good.
BUT  when i try to check this on my android browser it doesn't show any camera option..  
![WhatsApp Image 2020-04-05 at 2 04 20 AM](https://user-images.githubusercontent.com/22131381/78460917-a91a9700-76e2-11ea-8f18-ac91e7460719.jpeg)

**Comment by odahcam** [comment]
Well, the example pages is not a PWA (offline available app) so it's very possible that the browser messes the code when you try to save it. But don't worry, if you use this library inside a PWA it should work fine on an Android device.
