### ISSUE TITLE
Destroy method exists?

### ISSUE THREAD

**Issue by asaf050** [zxing-js/library#285]
Hi,
Can't find any documentation regarding destroy method when finish using the video stream.
Does such function exists or it done automatically using the GC?
Right now we manually execute the `stopStreams` command manually.

**Comment by arthurmmedeiros** [comment]
This is what I came up with to stop streaming when my component unmounts

```
const multiReader = new BrowserMultiFormatReader();

export default function CameraMode(){
  ....
  // stops camera from scanning when component unmounts
  useEffect(() => () => {
    multiReader.reset();
  }, []);

  return(
    .....
  )
}
```

**Comment by odahcam** [comment]
AS @arthurmmedeiros pointed out, the `reset` method should take care of that kind of thing for ya. GC will not be helpfull in this scenario. You can explore `reset` method in here: https://github.com/zxing-js/library/blob/9552ae4397ebcd25468087a60256ed441c7fac8c/src/browser/BrowserCodeReader.ts#L955-L966
