### ISSUE TITLE
Reading PDF-417 drivers license barcodes

### ISSUE THREAD

**Issue by kilomilo** [zxing-js/library#289]
Hey guys,

I'm wondering if anyone has had this same issue when trying to use this library for scanning PDF417 barcodes from images in nodejs.
I've got the library working and done lots of tests with various pdf417 barcode images from a bunch of drivers licenses for an app im trying to build.

However even though the images seem like great quality to me and scans perfectly with browser/phone based barcode scanners, this javascript implementation of zxing wont detect or decode the barcodes. I have ran these same barcode images through the zxing cli tool and it detects and decodes them with no issues. I have also played around a bit with changing the images to greyscale and decreasing the brightness too, but no luck getting this to work.

I've created an example app with fake drivers license images, and my implementation of this library. If anyone can take a look and provide me thoughts of what the problem may be would be greatly appreciated.

Here is the github example i setup:
[Github Repo](https://github.com/kilomilo/zxing-library-barcode-reading)

Thank you!

**Comment by odahcam** [comment]
Please, share images, values, code, provide things so we can help you. We can't do efficient help without that info, we don't know what you're struggling with and most of us have no time to look into your repo.

**Comment by kilomilo** [comment]
Thanks for commenting, as much as the repo is pretty straight forward as to what my code is and shows the images, here it is below:

```import { readFileSync } from 'fs';
import {
  BarcodeFormat,
  DecodeHintType,
  RGBLuminanceSource,
  BinaryBitmap,
  HybridBinarizer,
  MultiFormatReader,
} from '@zxing/library/esm5';
import { decode } from 'jpeg-js';

const detectAndScan = (fileData: Buffer) => {
  const barcodeScanner = new MultiFormatReader();
  const hints = new Map();
  const formats = [BarcodeFormat.PDF_417];
  const rawFileData = decode(fileData);

  try {
    hints.set(DecodeHintType.POSSIBLE_FORMATS, formats);
    hints.set(DecodeHintType.TRY_HARDER, true);

    barcodeScanner.setHints(hints);

    const len = rawFileData.width * rawFileData.height;

    const luminancesUint8Array = new Uint8ClampedArray(len);

    for (let i = 0; i < len; i++) {
      luminancesUint8Array[i] =
        ((rawFileData.data[i * 4] + rawFileData.data[i * 4 + 1] * 2 + rawFileData.data[i * 4 + 2]) /
          4) &
        0xff;
    }

    const luminanceSource = new RGBLuminanceSource(
      luminancesUint8Array,
      rawFileData.width,
      rawFileData.height,
    );

    const binaryBitmap = new BinaryBitmap(new HybridBinarizer(luminanceSource));

    const results = barcodeScanner.decode(binaryBitmap);

    return results;
  } catch (err) {
    console.error('Error Reading Barcode: ', err.message);
  }
};

const pdf417Image = readFileSync('barcode-scanned-clear-adjusted.jpg');
const pdf417Image2 = readFileSync('barcode-scanned-clear-bw.jpg');
const pdf417Image3 = readFileSync('fake-dl-pdf417.jpg');

const decodePdf417Results = detectAndScan(pdf417Image);
const decodePdf417Results2 = detectAndScan(pdf417Image2);
const startTime = Date.now();
const decodePdf417Results3 = detectAndScan(pdf417Image3);
const timeResults = Date.now() - startTime;

console.log('Results: ', {
  time: timeResults,
  fakeDlPdf417: decodePdf417Results?.getText(),
  fakeDlGreyscale: decodePdf417Results2?.getText(),
  fakeDlLicense: decodePdf417Results3?.getText(),
})```

Here are the image links for the PDF417 barcodes:
https://i.postimg.cc/HWMX72fC/fake-dl-pdf417.jpg
https://i.postimg.cc/qvFvwf3D/fake-drivers-license-greyscale.jpg
https://i.postimg.cc/qvFvwf3D/fake-drivers-license-greyscale.jpg

Thanks!

**Comment by odahcam** [comment]
Well, I did test with both Node and browser and none had successful results. Node thrown an encoding error saying the encoding I was using was not supported (probably my mistake here) and browser gave me this akward result:

``` 
@  AAMVA6360650101DL00290197DAQTQ157407H DAAMILES DANIEL RAE DAG196 WEST IRONWOOD DR DAICOEUR D'ALENE DAJID DAK83814 DARD DAS*/* DAT---- DAU600 DAYBLU DBA20180201 DBB19910201 DBCM DBD20120210 DBF00 DBHN
```

This is probably messed up like this because of browser's encoding, but the library did reconized the PDF417 code in the image, just was unable to decode it's values back to the original text.

If you're using Node you probably just got into the same encoding issue, to make sure you could test using the `PDF417Reader`, which makes all the sense, since you just need it. For example:

```typescript
// this example uses sharp, just ignore it 
// and use your own luminance source as you're already doing
SharpImage.loadWithRotation('./fake-drivers-license.jpg', 0).then(img => {

  const zxing = new PDF417Reader();

  const source = new SharpImageLuminanceSource(img);
  const bitmap = new BinaryBitmap(new HybridBinarizer(source));

  zxing.decode(bitmap);

});
```

**Comment by kilomilo** [comment]
Thanks for this, i did just try with just the PDF417Reader class and got the result "The "ISO-8859-1" encoding is not supported".
It actually looks like what you have there that you got from the browser is the correct result, the drivers licenses have some various extra hidden characters encoded.

So with this error being thrown, does that just mean i just wont be able to get these "ISO-8859-1" encoded results using this library and ill have to try and find a different library that can?

**Comment by odahcam** [comment]
Yep, it seems on the browser everything works fine and for Node there's a lot of ways of solving this, I just don't know why the default TextDecoder throws this unsupported errors, that's very odd. Using UTF-8 I was able to decode your images and using a third-party decoding library I could decode as well, but I had to make changes on the source for this to work, I'm still trying to figure out how to make this somehow configurable.

**Comment by kilomilo** [comment]
Ahh that makes sense, I really appreciate you looking into and trying to figure this out for me, I wish I knew more about decoding these barcodes and could put in a PR myself but it seems very complex.
If there is anything I can do to assist, feel free to let me know!

**Comment by odahcam** [comment]
Well, I created a very poor solution, but it solves (hehe) the problem for now:

```typescript
import { readFileSync } from 'fs';

import { decode } from 'jpeg-js';
import { RGBLuminanceSource, BinaryBitmap, HybridBinarizer } from '.';
import PDF417Reader from './core/pdf417/PDF417Reader';
import StringEncoding from './core/util/StringEncoding';

import { TextDecoder } from 'text-encoding';

StringEncoding.customDecoder = (stringContent, encodingName) => new TextDecoder(encodingName).decode(stringContent);

const barcodeScanner = new PDF417Reader();

const detectAndScan = (fileData: Buffer) => {
  const rawFileData = decode(fileData);

  try {

    const len = rawFileData.width * rawFileData.height;

    const luminancesUint8Array = new Uint8ClampedArray(len);

    for (let i = 0; i < len; i++) {
      luminancesUint8Array[i] =
        ((rawFileData.data[i * 4] + rawFileData.data[i * 4 + 1] * 2 + rawFileData.data[i * 4 + 2]) /
          4) &
        0xff;
    }

    const luminanceSource = new RGBLuminanceSource(
      luminancesUint8Array,
      rawFileData.width,
      rawFileData.height,
    );

    const binaryBitmap = new BinaryBitmap(new HybridBinarizer(luminanceSource));

    const results = barcodeScanner.decode(binaryBitmap);

    return results;
  } catch (err) {
    console.error('Error Reading Barcode: ', err.message);
  }
};

const pdf417Image = readFileSync('fake-drivers-license-greyscale.jpg');
const pdf417Image3 = readFileSync('fake-dl-pdf417.jpg');

const decodePdf417Results = detectAndScan(pdf417Image);
const startTime = Date.now();
const decodePdf417Results3 = detectAndScan(pdf417Image3);
const timeResults = Date.now() - startTime;

console.log('Results: ', {
  time: timeResults,
  fakeDlPdf417: decodePdf417Results ? decodePdf417Results.getText() : '',
  fakeDlLicense: decodePdf417Results3 ? decodePdf417Results3.getText() : '',
});
```

From that code, you can see that `StringEncoding` will support a `customDecoder` prop, in which you can set your own decoder, not depending on Node's flawed system.

Also, I've created a check that avoid Node's `TextDecoder` if the decoding format is ISO-8859-1 and directly uses the fallback system.

I'll be publishing v0.16.2 now.

**Comment by kilomilo** [comment]
Haha that sounds like a great solution and should work perfectly for me. Thanks for doing that so quick.
I see the new release is completed in github now, i assume yarn may take a bit to recognize the change, as it seems i can still only install 0.16.1 so far.

Ill let you know when i can update the package and confirm it works.

**Comment by odahcam** [comment]
It's on! v0.16.2 is now current.

**Comment by kilomilo** [comment]
I just confirmed the change works perfectly for me on my end.

Thanks again!
