### ISSUE TITLE
I am not able to scan barcode in the Landscape mode on mobile

### ISSUE THREAD

**Issue by Shababsoft** [zxing-js/library#291]
I am not able to scan the multi-format barcode on the landscape mode of the mobile, I have included the following in the page head so the scanning page looks good on mobile. However, it is working fine in portrait mode.

```
<head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
        <title>Barcode Scan</title>
 </head>

<style>
        .video {
            width: 100%;
        }
</style>
```

**Comment by odahcam** [comment]
Well, I have no problems doing that with the latest version.

**Comment by Shababsoft** [comment]
@odahcam  - Please can you try in landscape mode when rotation is locked to the portrait, please see the attached screenshot.

![Screenshot_20200417-210401](https://user-images.githubusercontent.com/4686730/79609744-2f75a680-80ef-11ea-8924-ba14234772f1.jpg)

**Comment by odahcam** [comment]
Oh, that explains a lot actually. Try enabling try-harder.

**Comment by Shababsoft** [comment]
@odahcam  - How can I enable the try-harder? Please can you provide me with an example (javascript code)?

**Comment by odahcam** [comment]
Ok, but first this is a dupe of: #226

You can find how to enable try harder...

- here https://github.com/zxing-js/library/issues/226#issuecomment-578098395
- here https://github.com/zxing-js/library/issues/148#issuecomment-479674044

And find how to use hints...

- here https://github.com/zxing-js/library/issues/136#issuecomment-463453611
- here https://github.com/zxing-js/library/issues/100#issuecomment-435046435

And probably lots of other places.

Pratical example:

**Comment by odahcam** [comment]
Ok, but first this is a dupe of: #226

You can find how to enable try harder...

- here https://github.com/zxing-js/library/issues/226#issuecomment-578098395
- here https://github.com/zxing-js/library/issues/148#issuecomment-479674044

And find how to use hints...

- here https://github.com/zxing-js/library/issues/136#issuecomment-463453611
- here https://github.com/zxing-js/library/issues/100#issuecomment-435046435

And probably lots of other places.

Pratical example:

```javascript
// load your ZXing library the way you want, then...
const { BrowserMultiFormatReader, DecodeHintType } = ZXing;

const hints = new Map();
hints.set(DecodeHintType.TRY_HARDER, true);
 
const reader = new BrowserMultiFormatReader();
 
reader.setHints(hints);

const firstDeviceId = videoInputDevices[0].deviceId;

codeReader
  .decodeOnceFromVideoDevice(firstDeviceId, 'video')
  .then(result => console.log(result.text))
  .catch(err => console.error(err));
``` 

That should do.

**Comment by Shababsoft** [comment]
The above code is working for me

**Comment by Shababsoft** [comment]
@odahcam  - Is there anyway to close the reader once the scan is completed? Like we can reset using the following code
`codeReader.reset();`

**Comment by odahcam** [comment]
You mean stop decoding without stopping the video?

**Comment by Shababsoft** [comment]
@odahcam  - Thanks is there a way to stopping video?

**Comment by odahcam** [comment]
`codeReader.reset();` will stop both video stream and decoding.

**Comment by minusdavid** [comment]
I take it that TRY_HARDER isn't available with zxing-js/browser?
