### ISSUE TITLE
Cordova support

### ISSUE THREAD

**Issue by vallettea** [zxing-js/library#299]
First, thanks for this awesome library.

I'm trying to use it inside a cordova application generated by quasar framework. However, I can't find a way to replace the html video tag by a native camera input from cordova. Do you have any idea on how I can do this ?

Thanks

**Comment by odahcam** [comment]
If you somehow have access to a `MediaStream` object from the video tag you could use this method: https://github.com/zxing-js/library/blob/8368266cba9a8adb0637eb62097d6495f036f22c/src/browser/BrowserCodeReader.ts#L342-L351

A `MediaStream` may be provided by the native video tag.

**Comment by vallettea** [comment]
thanks @odahcam , i'll check soon
