### ISSUE TITLE
bug: not working with image from canvas

### ISSUE THREAD

**Issue by albjeremias** [zxing-js/library#307]
**Describe the bug**
I want to have zxing working with a canvas.. And I can't get it to work

**To Reproduce**
I am using `getImageData` from a canvas context.. and using decode of zxing-js.. the result I get is: 

```TypeError: "CanvasRenderingContext2D.drawImage: Argument 1 could not be converted to any of: HTMLImageElement, SVGImageElement, HTMLCanvasElement, HTMLVideoElement, ImageBitmap.```

I was following the tips in https://github.com/zxing-js/library/issues/76 but the bug was closed automatically, so im not sure that it was solved.

**Comment by odahcam** [comment]
> TypeError: "CanvasRenderingContext2D.drawImage: Argument 1 could not be converted to any of: HTMLImageElement, SVGImageElement, HTMLCanvasElement, HTMLVideoElement, ImageBitmap.

Try passing the canvas element to the decode method instead.

**Comment by albjeremias** [comment]
uff, you are right.. sorry.. it says there
