### ISSUE TITLE
codeReader.reset() is not working

### ISSUE THREAD

**Issue by Hranasinghe** [zxing-js/library#310]
I used for barcode reader into a modal. If the user opens the modal, it triggered the initiateBarcodeScanner method. Then it scans a barcode value. it works perfectly. On the other hand user can cancel the modal. then I want to close the camera. So I called codeReader.rest() method. but it's not working. the camera still working. I want help to resolve it. Can you help me who related to this?

**Comment by Hranasinghe** [comment]
Sorry. It's my fault.

**Comment by odahcam** [comment]
Do you still need help with this?

**Comment by gauravcleartax** [comment]
How did you get it to work ?

**Comment by HarendraRanasinghe95** [comment]
@odahcam No, now it's resolved. Thanks

**Comment by HarendraRanasinghe95** [comment]
@gauravcleartax It's my frontend issue with state management. I think its not a bug.

**Comment by gauravcleartax** [comment]
I am also trying to call codeReader.reset() but it's not doing anything.

**Comment by HarendraRanasinghe95** [comment]
If you are using React, https://stackoverflow.com/questions/61953577/not-closing-camera-in-zxing This will be helpful for you

**Comment by gauravcleartax** [comment]
Okay thanks. I will check.
