### ISSUE TITLE
How to differentiate the type of the scanned code?

### ISSUE THREAD

**Issue by arthurmmedeiros** [zxing-js/library#321]
Hello there,

It's amazing that this library deals with many different types of code, it really does what I was looking for.

I was wondering if someone could share a way to tell which code is being scanned.

I'm using the multi reader class.

Should I consider that the property 'format' gives me this info?
format: 11 - > Qrcode
format: 7 - > Bar code

**Comment by Salketer** [comment]
You are right, ZXing.BarcodeFormat provides the list of all formats. You can cycle through the properties to find the right one... They are a Typescript ENUM so you cannot be certain that format 11 will always be QR_CODE... If you need to test to see if it is a specific type, simply test using `result.format === ZXing.BarcodeFormat.QR_CODE`

**Comment by Salketer** [comment]
I just realized, result.format is a private property. It would be safer to use `result.getBarcodeFormat()`

**Comment by arthurmmedeiros** [comment]
Thanks @Salketer
