### ISSUE TITLE
What is `timeBetweenScansMillis` supposed to do?

### ISSUE THREAD

**Issue by max2ti** [zxing-js/library#334]
In the comment it is described as:

`[timeBetweenScansMillis=500] the time delay between subsequent decode tries`

I was expecting the video stream to be "polled" every `timeBetweenScansMillis`, or similarly, for the library to wait `timeBetweenScansMillis` after having processed the previous frame before polling/processing the next one. I considered it a setting to let the the user choose between reactiveness but with high cpu usage, and slower detection rate but with lower cpu usage.

What I think I've seen profiling the code is that the library processes as many frames as it can regardless of `timeBetweenScansMillis`, but it waits `timeBetweenScansMillis` after a successful read before starting again. This makes `timeBetweenScansMillis` almost useless for the purpose of saving cpu, and leads me to believe that it was not its purpose at all.

So, what is the intended purpose of `timeBetweenScansMillis`?
Is there any way to lower cpu usage?

**Comment by odahcam** [comment]
I will spare us of the errors of the past and strictly recommend using the new browser layer, in which `timeBetweenScansMillis` was replaced by a useful alternative: https://github.com/zxing-js/browser

`timeBetweenScansMillis` was supposed to delay subsequent decode attempts after a successful one and not between every attempt. It's very confusing nature led to more confusion and bad implementations.
