### ISSUE TITLE
Unable to load module via requirejs or dojo loader

### ISSUE THREAD

**Issue by kenlyon** [zxing-js/library#339]
**Describe the bug**
I want to use `@zxing/library` in a project that loads dependencies asynchronously using a call to `require()`. We actually depend on the [dojo loader](https://dojotoolkit.org/reference-guide/1.10/loader/), but I have also tried [requirejs](https://requirejs.org/). In both cases, the `umd/index.min.js` file is loaded, but the variable that is expected to contain `ZXing` is `undefined`.

**To Reproduce**
1. `npm install @zxing/library` (or yarn or whatever)
2. Create a new html page.
3. Attempt to load ZXing via require, something like this:
(this is the dojo configuration syntax)
```
<script type="text/javascript">
    require({
        packages: [
            {
                name: "@zxing/library",
                location: "./node_modules/@zxing/library",
                main: "umd/index.min"
            }
        ]
    });
    require(["@zxing/library"], function(ZXing) {
        console.log(ZXing);
    });
</script>
```

**Expected behavior**
I expect the console to log an object of the ZXing module. Instead I get `undefined`.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 79.0

**Additional context**
A colleague suggested editing the `umd/index.min.js` file and removing the "ZXing" parameter from the call to `define()`. This allowed it to load for me. This would suggest that the use of a [module name](https://requirejs.org/docs/api.html#modulename) is complicating things.

**Comment by kenlyon** [comment]
This is still relevant for me. We're currently using a gross hack in our release build to remove the offending "ZXing" parameter. I'd love to be able to take that out.

**Comment by odahcam** [comment]
Have you tryied v0.18.1 out? I completely changed the build system used for the UMD bundle. Maybe this will help out. I'd love some help on testing it anyway, it seems to work throught HTML script tags tho.

**Comment by kenlyon** [comment]
We're currently using 0.17.1. I'll try 0.18.1 and let you know how it goes.

**Comment by odahcam** [comment]
There's an even newer release, v0.18.2. I'll try to setup an AMD load test in future versions as it is a very important thing that fails sometimes.

**Comment by kenlyon** [comment]
We've updated to 0.18.2 and it now works without the hack. Nice!

We'll keep watching the updates with interest as we've observed inconsistent results with certain barcodes and I see some recent changes in your history to address that.
