### ISSUE TITLE
Zxing js how to stop scanning properly

### ISSUE THREAD

**Issue by FFParf** [zxing-js/library#340]
I am integrating Zxing js to my web application. To stop the camera i am calling codeReader.Reset()

But that gives me this error(when i call it before scanning any codes): 'Video stream has ended before any code could be detected.'

My question is, is codeReader.Reset() the right way to stop the scanner/video? and what to do about that error?

Thanks in advance.

**Comment by nperepichka** [comment]
I have same issue...

**Comment by zacharytyhacz** [comment]
Hello @FFParf , I have a couple questions about your situation:

- Which code reader module of the package are you using? ( PDF417, QRcode, etc )
- Are you using the `codeReader.decodeOnceFromVideoDevice()` and `codeReader.listVideoInputDevices()` methods?

I've used these methods before with PDF417 and they turn off the stream correctly for me. However, yes, that message still shows as a warning for me. But also keep in mind that your browser will persist the camera permission for that page's tab, making it *seem* like it's still on.

**Comment by muziekklas** [comment]
Got the same issue when using the Angular component library, but I do think that the issue is in the core library.
Also note that the little LED of my webcam stays on and the camera cannot be used by another program except the website.
I am using Chrome on Windows 10

**Comment by KlausHans** [comment]
Got the same issue in Angular.
Here is my piece of code
```
    this.codeReader = new BrowserMultiFormatReader();
    this.codeReader.listVideoInputDevices()
      .then((videoDeviceList: MediaDeviceInfo[]) => {
        console.log("videoDeviceList", videoDeviceList);
        this.moreThanOneCamera = videoDeviceList.length > 1;
        this.changeDetector.detectChanges();
        this.videoDeviceId = this.localStorageService.getStorageItem<string>(LocalStorageKey.ScanVideoDeviceId);

        this.codeReader.decodeOnceFromVideoDevice(this.videoDeviceId, 'video')
          .then(result => console.log(result))
          .catch(err => console.log(err));
      })
      .catch(err => console.log(err));
```
If i do nothing in `ngOnDestroy()` the camerastream is still open if the component is destroyed. If i call `this.codeReader.reset();` in `ngOnDestroy()` i get the error `NotFoundException: Video stream has ended before any code could be detected.`

**Comment by odahcam** [comment]
@KlausHans your method is not wrong, you just need to wrap that reset call in a try-catch block so it can [oddly] inform you with exceptions if something didn't endup as expected. This expcetions throw confuses everyone and I'm looking forward to change it.

**Comment by odahcam** [comment]
Hey guys, take a look on the new browser layer: https://github.com/zxing-js/browser

It features way better scan handling and allows you to stop the continuous scan by simply calling a function received from each continuous decode call. That means we can have now multiple continuous scans running for multiple devices, or videos, etc. As I said, way better scan handling.

**Comment by tdelam** [comment]
> 

What if we don't want to stop controls after a scan but want to use a lifecycle method such as when a component is unmounting or in stimulus `disconnect()`?
