### ISSUE TITLE
Creating datamatrix module

### ISSUE THREAD

**Issue by mpodlasin** [zxing-js/library#35]
My company needs in-browser datamatrix scanning asap.

Thus I am starting now to port zxing datamatrix module to ts, based on this project.

Will you be willing to code review it, test and merge it once its ready? Can I expect some help in case I am stuck?

Thanks in advance and have a great day. :)

**Comment by odahcam** [comment]
Get in touch whenever you want: https://gitter.im/zxing-js

We are **very** glad by receiving contributions and we'r gonna help.

**Comment by odahcam** [comment]
Consider it done, publishing it by the weekend, and that's by me. Thx.

**Comment by BenjaminAbt** [comment]
Is there a scheduled release day for 0.6.0 or a beta version to test this?
Thanks, Ben

**Comment by odahcam** [comment]
It should be available on the latest dev build: `npm i -S @zxing/library@dev`.

**Comment by wishmaster-** [comment]
the library I install via "npm i -S @zxing/library@dev" seems not to be able to scan a Datamatrix code (ecc200).
I also noticed, that most of the recent commits in the dev branch differ from my installed "@dev" version.
It might well be possible that the fault is on my side, since I am rather new to JavaScript and Node.js.

**Comment by odahcam** [comment]
Please take a try on `npm i -S @zxing/library@beta`. 🙂

**Comment by wishmaster-** [comment]
@odahcam I updated the library to the beta version and the scanner to the latest dev version. But my sample Datamatrix Code is not recognized. QR Codes work fine. Don't know what about barcodes, but those are not recognized either.
These are my currently used versions:
    "@zxing/library": "^0.6.0-beta.1",
    "@zxing/ngx-scanner": "^1.2.0-dev.980c03",

**Comment by odahcam** [comment]
Well, I think you're just using the wrong reader for your task, for example you may be using `ZXing.BrowserQRCodeReader` and trying to read a DataMatrix, but you need a DataMatrixReader in that case.

**Comment by odahcam** [comment]
Also, I'd like to invite you to join [our Gitter chat](https://gitter.im/zxing-js/library).
