### ISSUE TITLE
iOS WKWebView - scan static image working?

### ISSUE THREAD

**Issue by capc0** [zxing-js/library#350]
I know that WebRTC is not (fully) supported by iOS.

However since this library can also extract/scan static images, has anyone tried to use that feature in an ionic/cordova environment running on iOS?

kinda related to https://github.com/zxing-js/library/issues/15, but that issue is locked.

**Comment by odahcam** [comment]
Hello, this is also related to #149 . In short, only media devices API doesn't work on iOS webview, the rest of the functions should work fine.
