### ISSUE TITLE
 How to resolve - Uncaught SyntaxError: Unexpected token 'export'?

### ISSUE THREAD

**Issue by suriyaJaay** [zxing-js/library#354]
Hi,

I'm trying to use Zxing.JS with my Angular.1x app. where it has using gulp task runner. (am not completely familiar with gulp configs and setup). so Whenever i use  `gulp karmaRunDebug`, am getting **Uncaught SyntaxError: Unexpected token 'export'**. due to this my CI/CD getting failed.

I've attached the image below. 

Someone pls help me on this..!!
![zxing import issue](https://user-images.githubusercontent.com/19813670/95545547-cd518a80-0a1b-11eb-8484-8f1ccd250194.PNG)

**Comment by odahcam** [comment]
Please, try the latest version (v0.18.2). Thansk!
