### ISSUE TITLE
ES6 Bundle as default

### ISSUE THREAD

**Issue by werthdavid** [zxing-js/library#355]
When using with Angular 10, the following warning is thrown:

WARNING in workspace\ngx-scanner\projects\zxing-scanner-demo\src\app\app.component.ts depends on '@zxing/library'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by odahcam** [comment]
It's published!
