### ISSUE TITLE
unpkg breaking with changes

### ISSUE THREAD

**Issue by QuijoteShin** [zxing-js/library#359]
Hi, the latest commit are breaking the export  since the move out from **es5** .

The error reported from unpkg:

```
library@latest:12 Uncaught ReferenceError: exports is not defined
    at library@latest:12

```
There may be some es5 dependency  generating this line:

`Object.defineProperty(exports, "__esModule", { value: true });`

Will try to check wich one.

Hoping to help more,
qshin.

**Comment by odahcam** [comment]
Thanks for reporting, it should be fixed on [v0.18.2](https://unpkg.com/browse/@zxing/library@0.18.2).
