### ISSUE TITLE
get TypeError: callbackFn is not a function when using decodeFromVideoDevice() 

### ISSUE THREAD

**Issue by ratiw** [zxing-js/library#360]
I'm on version 0.18.2 of the library, trying to use this library according to the code in this example, `https://github.com/zxing-js/library/blob/master/docs/examples/multi-camera/index.html`. Somehow, got the following error in the console.

`TypeError: callbackFn is not a function`

However, when replacing `decodeFromVideoDevice()` with `decodeOnceFromVideoDevice()`, everything is working fine.

**Desktop (please complete the following information):**
 - OS: iOS 10.15.7
 - Browser: Firefox
 - Version: 81.0.1 (64-bit)

**Comment by odahcam** [comment]
It seems to work from the website.
 ![Screenshot_20201021-122733.png](https://user-images.githubusercontent.com/3942006/96742555-6fb52a80-1399-11eb-964a-8a1dcc23c7d0.png)

Could you share the exact code you're using?

**Comment by ratiw** [comment]
I'm trying to use this in [Alpine.js](https://github.com/alpinejs/alpine) by following the example. In v18.1, the day before it wasn't working at all due to error about `exports is not defined` or something (sorry, I couldn't remember it exactly). But yesterday I saw v18.2, and retry it and it seems to work, except when I use `decodeFromVideoDevice()` as I mentioned in the earlier post.

Here is the code. It might not be familiar to you but a lot of syntax of Alpine.js was borrowed/followed those in the Vue.js.

```javascript
<body>
<div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-md-12 col-lg-10">
        <div x-data="setup()" x-init="getCameras()" class="scanqr d-flex flex-column align-items-center p-3">
          <select x-model="activeCamera" x-on:change="selectCamera($event.target.value)" name="select_camera" class="custom-select mb-2">
            <option value="">-- select camera --</option>
            <template x-for="(camera, idx) in devices" :key="camera.deviceId">
              <option :value="camera.deviceId" x-text="camera.label"></option>
            </template>
          </select>
          <video id="video" width="600" height="400" class="border-1"></video>
          <button x-on:click="closeCamera()" class="btn btn-default mt-3">Stop camera</button>
        </div>
      </div>
    </div>
</div>
</body>
<script src="https://unpkg.com/@zxing/library@latest"></script>
<script type="text/javascript" src="/assets/admin/vendors/beep.js"></script>
<script type="text/javascript">

    function setup() {
      return {
          devices: [],
          activeCamera: null,
          scanner: new ZXing.BrowserMultiFormatReader(),

          getCameras() {
            this.scanner.listVideoInputDevices().then(devices => {
              this.devices = devices
            })
            .catch(err => console.error('getCamera:', err))
          },

          selectCamera(id) {
            console.log('selecting camera ', id)
            if (this.activeCamera) {
              this.closeCamera()
            }

            this.activeCamera = id
            this.scanner.decodeOnceFromVideoDevice(id, 'video').then(result => {
              this.scanSuccess(result)
            })
            .catch(err => {
              if (err && !(err instanceof ZXing.NotFoundException)) {
                console.log('selectCamera:', err)
              }
            })
          },

          closeCamera() {
            if (this.scanner) {
              this.activeCamera = null
              this.scanner.reset()
              console.log('camera has been reset.')
            }
          },

          scanSuccess(message) {
            new Beep(22050).play(1000, 0.2, [Beep.utils.amplify(8000)]);
            console.log('scan success', message)
            this.closeCamera()
          }
        }
      }
</script>
```

**Comment by odahcam** [comment]
Ok, I saw this error and managed to get rid of it in the new browser layer, could you give it a try? (https://github.com/zxing-js/browser)

**Comment by ratiw** [comment]
Unfortunately, the link [https://unpkg.com/@zxing/library@latest](https://unpkg.com/@zxing/library@latest) is still pointing to v.0.18.2 and I still got the same error.

**Comment by odahcam** [comment]
On the **new browser layer**:  https://unpkg.com/@zxing/browser@latest

**Comment by ratiw** [comment]
Sorry, but do I have to put this before or after the zxing/library?

**Comment by ratiw** [comment]
Tried putting the script line both before and after `@zxing/labrary` and still got the same error message. By the way, the link should be [https://unpkg.com/@zxing/browser@0.0.1-beta.1/](https://unpkg.com/@zxing/browser@0.0.1-beta.1/) without the word `/browse`.

**Comment by odahcam** [comment]
Yeah it should, hehe. I figure out that you would notice that and make proper use. In short, if you're only using the browser layer, you won't need to import the Library in your page and instead of using `ZXing.<something>` you will have `ZXingBrowser.<something>`.

**Comment by ratiw** [comment]
Now, I use only `"https://unpkg.com/@zxing/browser@0.0.1-beta.2/umd/zxing-browser.js` and instantiate the variable using
```js
    this.scanner = new ZXingBrowser.BrowserMultiFormatReader()
```
But it seems the API for ZXingBrowser is different than in ZXing as I have to use 
```js
    ZXingBrowser.BrowserMultiFormatReader.listVideoInputDevices()
```

instead of `this.scanner.listVideoInputDevices()` as in the example. Also, the `reset()` function is no longer exist, as well as `NotFoundException` class.

Anyway, result is still the same, the `decodeOnceFromVideoDevice()` works, but not `decodeFromVideoDevice()`.  Still got the same error `callbackFn is not a function`, followed by `ImageCapture is not defined`.

**Comment by odahcam** [comment]
Please make sure you are correctly using the method:

```typescript
            this.scanner.decodeFromVideoDevice(id, 'video', (result, err) => {
              if (err) {
                if (err && !(err instanceof ZXing.NotFoundException)) {
                  console.log('selectCamera:', err)
                }
                return;
              } // else
              this.scanSuccess(result);
            })
```

If you do not pass the third argument you will indeed get the `callbackFn` error.
`ImageCapture` is used to check if torch is available, I think it's better to surround that block with a try-catch and ignore this error, because browsers that doesn't support full webrtc will throw this error and probably break code execution.

**Comment by ratiw** [comment]
Oh, sorry. That was my bad. I didn't notice the API difference between `decodeOnceFromVideoDevice()` and `decodeFromVideoDevice()`. 

After calling `decodeFromVideoDevice()` with the callback function in the 3rd parameter, it is now working as expected.

Sorry for the trouble and really thank you for pointing me out.

Cheers,
