### ISSUE TITLE
nodejs not working \w sample code

### ISSUE THREAD

**Issue by k1r0s** [zxing-js/library#364]
https://github.com/zxing-js/library/issues/148#issuecomment-479674044

it does not work with the latest version

i keep receiving: '(node:27418) UnhandledPromiseRejectionWarning: Error: SOI not found' all time

```javascript
const { MultiFormatReader, BarcodeFormat, DecodeHintType, RGBLuminanceSource, BinaryBitmap, HybridBinarizer } = require('@zxing/library');
const fs = require('fs');
const jpeg = require('jpeg-js');

const readFile = path => new Promise((resolve, reject) => fs.readFile(path, (err, content) => {
  if(err) return reject(err);
  else return resolve(content);
}))

readFile('Qr-1.png').then(jpegData => {
  const rawImageData = jpeg.decode(jpegData);


  const hints = new Map();
  const formats = [BarcodeFormat.QR_CODE, BarcodeFormat.DATA_MATRIX];

  hints.set(DecodeHintType.POSSIBLE_FORMATS, formats);
  hints.set(DecodeHintType.TRY_HARDER, true);

  const reader = new MultiFormatReader();

  reader.setHints(hints);



  const len = rawImageData.width * rawImageData.height;

  const luminancesUint8Array = new Uint8Array(len);

  for(let i = 0; i < len; i++){
  	luminancesUint8Array[i] = ((rawImageData.data[i*4]+rawImageData.data[i*4+1]*2+rawImageData.data[i*4+2]) / 4) & 0xFF;
  }

  const luminanceSource = new RGBLuminanceSource(luminancesUint8Array, rawImageData.width, rawImageData.height);

  console.log(luminanceSource)

  const binaryBitmap = new BinaryBitmap(new HybridBinarizer(luminanceSource));


  const decoded = reader.decode(binaryBitmap);

  console.log(decoded)
})

```

**Comment by odahcam** [comment]
I don't think this is a bug with the Library. Some starting points for investigation: 

- https://github.com/serratus/quaggaJS/issues/298#issuecomment-397845345

I know it may sound a bit off to ask, but are you trying to load an image that **is not** a JPEG file with this example code?

**Comment by k1r0s** [comment]
it might be. I tried lots of images. Some do work, others don't. And I don't see a strong relationship between image formats

**Comment by odahcam** [comment]
Well, first of all, are you using JPEG files?

**Comment by k1r0s** [comment]
will report you back on this

**Comment by odahcam** [comment]
This example you pasted should only work with JPEG files.

**Comment by prdpjngd** [comment]
> [#148 (comment)](https://github.com/zxing-js/library/issues/148#issuecomment-479674044)
> 
> it does not work with the latest version
> 
> i keep receiving: '(node:27418) UnhandledPromiseRejectionWarning: Error: SOI not found' all time
> 
> ```js
> const { MultiFormatReader, BarcodeFormat, DecodeHintType, RGBLuminanceSource, BinaryBitmap, HybridBinarizer } = require('@zxing/library');
> const fs = require('fs');
> const jpeg = require('jpeg-js');
> 
> const readFile = path => new Promise((resolve, reject) => fs.readFile(path, (err, content) => {
>   if(err) return reject(err);
>   else return resolve(content);
> }))
> 
> readFile('Qr-1.png').then(jpegData => {
>   const rawImageData = jpeg.decode(jpegData);
> 
> 
>   const hints = new Map();
>   const formats = [BarcodeFormat.QR_CODE, BarcodeFormat.DATA_MATRIX];
> 
>   hints.set(DecodeHintType.POSSIBLE_FORMATS, formats);
>   hints.set(DecodeHintType.TRY_HARDER, true);
> 
>   const reader = new MultiFormatReader();
> 
>   reader.setHints(hints);
> 
> 
> 
>   const len = rawImageData.width * rawImageData.height;
> 
>   const luminancesUint8Array = new Uint8Array(len);
> 
>   for(let i = 0; i < len; i++){
>   	luminancesUint8Array[i] = ((rawImageData.data[i*4]+rawImageData.data[i*4+1]*2+rawImageData.data[i*4+2]) / 4) & 0xFF;
>   }
> 
>   const luminanceSource = new RGBLuminanceSource(luminancesUint8Array, rawImageData.width, rawImageData.height);
> 
>   console.log(luminanceSource)
> 
>   const binaryBitmap = new BinaryBitmap(new HybridBinarizer(luminanceSource));
> 
> 
>   const decoded = reader.decode(binaryBitmap);
> 
>   console.log(decoded)
> })
> ```

const fs = require('fs');
const {BarcodeFormat,
    MultiFormatReader,
    ZXingStringEncoding,
    PDF417DecodedBitStreamParser,
    DecodeHintType,
    RGBLuminanceSource, 
    BinaryBitmap, 
    HybridBinarizer} = require('@zxing/library')

async function decode(url) {
	return new Promise((resolve, reject) => {
		const webImgUrl = url
		Jimp.read(webImgUrl)
			.then((webImg) => {
				
					const len = webImg.bitmap.width * webImg.bitmap.height
					const luminancesUint8Array = new Uint8Array(len)
					for (let i = 0; i < len; i++) {
						luminancesUint8Array[i] = ((webImg.bitmap.data[i * 4] + webImg.bitmap.data[i * 4 + 1] * 2 + webImg.bitmap.data[
							i *
							4 + 2]) / 4) & 0xFF
					}
					const hints = new Map();
					const formats = [BarcodeFormat.QR_CODE, BarcodeFormat.DATA_MATRIX,BarcodeFormat.PDF_417,BarcodeFormat.AZTEC];

					hints.set(DecodeHintType.POSSIBLE_FORMATS, formats);

					const reader = new MultiFormatReader();

					reader.setHints(hints);

					const luminanceSource = new RGBLuminanceSource(luminancesUint8Array, webImg.bitmap.width, webImg.bitmap.height)
					const binaryBitmap = new BinaryBitmap(new HybridBinarizer(luminanceSource))
					const decoded = reader.decode(binaryBitmap)
					console.log(decoded)
					//did.push(decoded.text)
			}).catch(e => {
				console.log(e, reject)
				resolve('')
			})
	})
}
decode('5.jpg')

**Comment by prdpjngd** [comment]
> it might be. I tried lots of images. Some do work, others don't. And I don't see a strong relationship between image formats

```
const Jimp=require('Jimp')
const {BarcodeFormat,
    MultiFormatReader,
    DecodeHintType,
    RGBLuminanceSource, 
    BinaryBitmap, 
    HybridBinarizer} = require('@zxing/library')



async function decode(url) {
	return new Promise((resolve, reject) => {
		const webImgUrl = url
		Jimp.read(webImgUrl)
			.then((webImg) => {
				
					const len = webImg.bitmap.width * webImg.bitmap.height
					const luminancesUint8Array = new Uint8Array(len)
					for (let i = 0; i < len; i++) {
						luminancesUint8Array[i] = ((webImg.bitmap.data[i * 4] + webImg.bitmap.data[i * 4 + 1] * 2 + webImg.bitmap.data[
							i *
							4 + 2]) / 4) & 0xFF
					}
					const hints = new Map();
					const formats = [BarcodeFormat.QR_CODE, BarcodeFormat.DATA_MATRIX,BarcodeFormat.PDF_417,BarcodeFormat.AZTEC];

					hints.set(DecodeHintType.POSSIBLE_FORMATS, formats);

					const reader = new MultiFormatReader();

					reader.setHints(hints);

					const luminanceSource = new RGBLuminanceSource(luminancesUint8Array, webImg.bitmap.width, webImg.bitmap.height)
					const binaryBitmap = new BinaryBitmap(new HybridBinarizer(luminanceSource))
					const decoded = reader.decode(binaryBitmap)
					console.log(decoded)
					//did.push(decoded.text)
			}).catch(e => {
				console.log(e, reject)
				resolve('')
			})
	})
}
decode('5.jpg')
```
