### ISSUE TITLE
RSSExpandedReader fills console log with NotFoundException

### ISSUE THREAD

**Issue by Swiftwork** [zxing-js/library#367]
**Describe the bug**
The RSSExpandedReader fills the console with NotFoundException log messages, ~~even when only a single 1D format is enabled in `MultiFormatReader` with `hints.set(DecodeHintType.POSSIBLE_FORMATS, [BarcodeFormat.EAN_13]);`~~ **edit:** use `decodeWithState()` instead of `decode` to avoid overwriting existing hints.

**To Reproduce**
Steps to reproduce the logging behavior:
1. Go to [the demo page](https://zxing-js.github.io/library/examples/multi-camera/)
2. Open debug panel and console with F12 and ESC
2. On demo page click start
4. See logging in console

**Expected behavior**
1. Silently fail when pairs cannot be found.
2. ~~RSSExpandedReader is not run when not among possible formats.~~

**Screenshots**
![image](https://user-images.githubusercontent.com/455178/98443676-0d845580-210d-11eb-80d6-511db5a2c145.png)

**Additional context**
Relevant code https://github.com/zxing-js/library/blob/0dba01bc99bbe5a47d224d8a0d4c0c7c6fad81c3/src/core/oned/rss/expanded/RSSExpandedReader.ts#L97-L113

Great job on the library @odahcam !

**Comment by Swiftwork** [comment]
Deemed to be two separate issues. Using the code shown in the example I seem to get different outcomes. When use `setHints()` it includes RSSExpanded however, I am guessing it includes more formats and the `setHints()` is ignored.

```typescript
const { MultiFormatReader, BarcodeFormat } = require('@zxing/library/esm5'); // use this path since v0.5.1

const hints = new Map();
const formats = [BarcodeFormat.QR_CODE, BarcodeFormat.DATA_MATRIX/*, ...*/];

hints.set(DecodeHintType.POSSIBLE_FORMATS, formats);

const reader = new MultiFormatReader();

reader.setHints(hints);

const luminanceSource = new RGBLuminanceSource(imgByteArray, imgWidth, imgHeight);
const binaryBitmap = new BinaryBitmap(new HybridBinarizer(luminanceSource));

reader.decode(binaryBitmap);
```
While setting hints only on `decode` seems to produce the desired result of only using specified formats.
```typescript
const { MultiFormatReader, BarcodeFormat } = require('@zxing/library/esm5'); // use this path since v0.5.1

const hints = new Map();
const formats = [BarcodeFormat.QR_CODE, BarcodeFormat.DATA_MATRIX/*, ...*/];

hints.set(DecodeHintType.POSSIBLE_FORMATS, formats);

const reader = new MultiFormatReader();

const luminanceSource = new RGBLuminanceSource(imgByteArray, imgWidth, imgHeight);
const binaryBitmap = new BinaryBitmap(new HybridBinarizer(luminanceSource));

reader.decode(binaryBitmap, hints);
```
Unfortunately I am running in a web worker and have trouble setting breakpoints or debugging the code and I can't find any reason for this in the source code. Could you see if you detect what I am missing @odahcam?

**Comment by Swiftwork** [comment]
As an answer to my own question this is due to the fact that `decode` does not maintain "hints state". The README example should end with the line:

```typescript
reader.decodeWithState(binaryBitmap);
```

else it will overwrite the previously set hints with `null`.

**Comment by odahcam** [comment]
Sorry but the RSS-Expanded is not production ready. I'll take time to proper read and try to help with the issue later. Thanks for the patience.

**Comment by Swiftwork** [comment]
@odahcam I am talking about the common.js instructions at 
https://github.com/zxing-js/library/blob/master/README.md#use-outside-the-browser-with-commonjs
it suggests the usage of `reader.decode(binaryBitmap);`, but this should be `reader.decodeWithState(binaryBitmap);` or `reader.decode(binaryBitmap, hints);` else the hints are lost.

The other issue is easily reproducible by following the steps outlined above ;). This is on npm released version 0.18.3 and can be observed on the GitHub demo page.

**Comment by Hopingocean** [comment]
how to solve this problem?

**Comment by Hopingocean** [comment]
how to solve this problem?

**Comment by Swiftwork** [comment]
@Hopingocean the comments don't solve the primary issue which is, as the title states, "RSSExpandedReader fills console log with NotFoundException". The reason for the issue in the title, is primarily that the `RSSExpandedReader` is not ready for usage yet, but has been merged to master. This, I guess, is for testing purposes (maybe better to be merged to development).

The issue the comments above addressed was the fact that `RSSExpandedReader` was activated even though it was not requested. Which is due to the README missing that `reader.decode(binaryBitmap);` should be `reader.decodeWithState(binaryBitmap);`.

I would generally advice avoiding changing the library files directly as each update will remove these changes 😄

**Comment by mrauter** [comment]
what is the workaround for decodeFromVideoDevice

**Comment by Swiftwork** [comment]
Closed by https://github.com/zxing-js/library/pull/381, but the underlying issue is still present. RSSExpanded is not ready for usage yet.
