### ISSUE TITLE
Camera not opening on mobile devices

### ISSUE THREAD

**Issue by josemarinas** [zxing-js/library#392]
**Describe the bug**
Camera does not open on some mobile devices, on desktop works perfectly.
This only happened on some devices and with some browsers for example when I use an iPhone 11 with Safari, it opens the camera and scans perfectly but if I change to Chrome or Firefox it throws the following error:
```
Error: Can't enumerate devices, method not supported.
```
This happened to me with other devices like Samsung Galaxy S20 (Chrome and Firefox). But if I try with an older phone like Google Pixel XL it works with both Chrome and Firefox.
I also tested accessing my web application and the [demo](https://zxing-js.github.io/library/examples/multi-camera/) provided with the same results in both websites

**To Reproduce**
1. Open a tab on Chrome in a mobile phone
2. Go to `chrome://inspect`
3. Click on "Start Log"
4. Open a new tab and go to https://zxing-js.github.io/library/examples/multi-camera/
5. Click on "Start"
6. Go back to the Chrome Inspect tab an check the errors

**Expected behavior**
It is expected to ask for camera permissions, and once they are granted start a video stream to scan the barcode

**Screenshots**
![photo_2021-01-06_18-34-58](https://user-images.githubusercontent.com/36479864/103801357-e9ca8680-504d-11eb-9414-9ceda4ae26e6.jpg)
![photo_2021-01-06_18-34-49](https://user-images.githubusercontent.com/36479864/103801367-ed5e0d80-504d-11eb-8c66-dd425f7e8dc8.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: 14.0
 - Browser: Chrome, Firefox

**Additional context**
The only pattern I saw is that this happens with phones with more than 1 back cameras

**Comment by timkley** [comment]
Fan confirm iPad with iOS 14.2. Working in Safari but not Chrome. Camera permissions have already been granted for Chrome.

**Comment by odahcam** [comment]
https://github.com/zxing-js/ngx-scanner/wiki/Limitations
