### ISSUE TITLE
Continues to print NotFoundException after reset() was called for variable amount of time.

### ISSUE THREAD

**Issue by LyDawei** [zxing-js/library#402]
**Describe the bug**
I currently have something similar to this in my app:

```
this.codeReader = new ZXing.BrowserMultiFormatReader();
this.codeReader
      .decodeOnceFromVideoDevice(undefined, 'camera')
      .then(res => {
        this.codeReader.reset();
        return res.text;
      });
```

The problem I'm noticing is, the console continues to spit out "NotFoundException" even after a successful scan. Is there something I'm missing about how to shut off the scan upon a successful scan?

**To Reproduce**
Start a multiformat scanner, upon successful scan do `.then(() => this.codeReader.reset())`. The camera does turn off, but notice the console continues to log exceptions for variable amount of seconds before stopping.

**Expected behavior**
Scanning should complete, close, and not continue to log into the console as if the scanning were still trying.

**Screenshots**
<img width="622" alt="Screen Shot 2021-01-29 at 2 42 19 PM" src="https://user-images.githubusercontent.com/10214577/106325314-3d408680-6240-11eb-9b76-0baef5e9c8ab.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome,safari
 - Version 0.18.3

**Smartphone (please complete the following information):**
 - Device: Apple devices
 - OS: iOS14
 - Browser Safari

**Sandbox**
https://codepen.io/LyDaWei/pen/wvoBbVz

Please open the dev tools, do a successful scan and the camera will shutoff, notice that the console continues to print "NotFoundException" for a variable amount of time.

**Comment by odahcam** [comment]
For browser usage please use https://github.com/zxing-js/browser
