### ISSUE TITLE
How To Disable NotFoundException console.log 

### ISSUE THREAD

**Issue by sabasayer** [zxing-js/library#412]
There are many NotFoundException console.log at the console.

Are there any way to disabled that

![image](https://user-images.githubusercontent.com/45066901/107944886-de993d80-6f9f-11eb-8da1-35ead9eb75fe.png)
![image](https://user-images.githubusercontent.com/45066901/107944919-e9ec6900-6f9f-11eb-9755-ea5de173066a.png)

**Comment by lnhrdt** [comment]
I came here after seeing the same issue. It seems like this was fixed in #381 and released in version 0.18.4, but that version is missing from npm (issue #408).

@odahcam any chance you can help get 0.18.4 published to npm?

**Comment by odahcam** [comment]
Hey thanks for remembering me of publishing this. There was some problem and I forgot to retry.

**Comment by mxcd** [comment]
@odahcam 
Could you pls update the peerDependency in the browser repo as well?
https://github.com/zxing-js/browser/blob/master/package.json#L57
Thanks a lot!
