### ISSUE TITLE
Incorrect reference to iOS Chrome support

### ISSUE THREAD

**Issue by egfx** [zxing-js/library#416]
The readme is indicating that there is support for Chrome on iOS.

> iOS 14.3 (released in december 2020) now supports WebRTC in 3rd party browsers as well 🎉

As far as I can tell this isn't the case. iOS 14.4 doesn't have support in chrome webview. I haven't tested PWA. Which 3rd party browser is this supposed to be working in?

**Comment by odahcam** [comment]
https://blog.bitsrc.io/ios-14-3-brings-webrtc-to-wkwebview-closing-gap-on-ios-accessibility-90a83fa6bda2
