### ISSUE TITLE
When is the datamatrix module be available ?

### ISSUE THREAD

**Issue by AJ-Thomas** [zxing-js/library#44]
Hi, i have seen that someone already worked on the datamatrix module, so i was wondering when it will be available ? 

Thanks.

**Comment by odahcam** [comment]
I dunno, we are working on both Data Matrix and EAN13 decoders, I was planning to release it at v0.6.0. Do  you need this feature right now?

**Comment by AJ-Thomas** [comment]
I am currently working on a project which need QRCode and Datamatrix decode, so if you could tell me when you were planning to release V0.6.0 or if i could get the datamatrix module , it would be nice.

**Comment by odahcam** [comment]
Right, we still gotta set some things up before the release, probably it will happen in something like one month.

**Comment by AJ-Thomas** [comment]
oh ok but is there a way to use the datamatrix module right now or i have to wait the release ?

**Comment by odahcam** [comment]
This week we probably gonna have a dev release, so you can use that release.

**Comment by AJ-Thomas** [comment]
oh on the develop branch ? nice

**Comment by odahcam** [comment]
Yep, I'll notify here when published.

**Comment by odahcam** [comment]
A new release was published yesterday, things are going fast, so by the weekend both DataMatrix and EAN13 will be available in a dev release.

**Comment by AJ-Thomas** [comment]
NICE to hear, also if you could include a small example for datamatrix that would be great.

**Comment by odahcam** [comment]
I will close this now, you can subscribe to #35 to more information. 🙂
