### ISSUE TITLE
Show scan result in input field

### ISSUE THREAD

**Issue by Jonnas123** [zxing-js/library#473]
Hello, the scan inputs the result into paragtraph tag, ex `<p id="result"></p>` How can I get the result in the input field to get its value? I've tried this `<input id="result"></input>` but doesn't work. I'm new to JS and library.

**Comment by Topya123** [comment]
Work for me.

<input id="result" type="text" name="" value="">
document.getElementById('result').value = result.text;

**Comment by mircerlancerous** [comment]
Seems like you've answered your own question. If you don't need anything further, you should close this issue
