### ISSUE TITLE
No Rear Camera Use in Browser

### ISSUE THREAD

**Issue by keithkk** [zxing-js/library#49]
Device: Pixel 2 XL
Browser: Chrome 67.0.3396.68
OS: Android 8.1.0

Tried both Scan QR Code from Video Camera and Scan Barcode from Image options, toggled dropdown menu that did indicate Camera 0 Front and Camera 1 Rear, Start, Reset, and the rear facing camera would never display in the window to scan from.

I also tried the same thing on a different fork that had the same issue and did not work correctly.

My objective is to scan UPC barcodes with my rear-facing camera.

**Comment by odahcam** [comment]
Right, I had the same problem that you has, but my case was in the `ngx-scanner` package, where we already solved this issue. I think it is a question of taking the solution from there and put it here.

**Comment by odahcam** [comment]
I'm just afraid that UPC barcodes aren't supported yet. 😕

**Comment by keithkk** [comment]
Thanks for the reply. I've had hit or miss luck when testing different browser-based scanners and the rear camera being the one to get triggered successfully. Native apps work just about every time provided they were built correctly with hardware directives. With the browser scanners though, when they trigger the front camera, I can't think of a time that I have not been able to read from the front since I usually still test it to see. I'm usually scanning UPC, EAN, and other product specific identifiers,

I'll circle back around in the future to test again.

**Comment by odahcam** [comment]
I gonna close this one for now. It's a little off topic.
