### ISSUE TITLE
How can i use this library in my App?

### ISSUE THREAD

**Issue by helloo0-0oword** [zxing-js/library#53]
Hello, I think this library is very cool. But how can i use in my app ? . Thank you. I'm from Vietnamese and i'm a student

**Comment by odahcam** [comment]
[This didn't help](https://github.com/zxing-js/library#usage)?

**Comment by helloo0-0oword** [comment]
No, I don't know. I think this library just use for browser. Because i don't see any example for React Native :( . And my last question is: When I select a qr code from the library then I want to decode it. that's fine Can you help me please :( ? Thank you very much

**Comment by helloo0-0oword** [comment]
I import: import { BrowserCodeReader } from '@zxing/library'
use: BrowserCodeReader.decodeFromImage('img-to-decode', 'https://www.unitag.io/images/generator/templates/classic.png').then(result => console.log(result))
is that right ?

**Comment by odahcam** [comment]
I'm afraid that `BrowserCodeReader` was built for browsers, not React Native. Try use the core `MultiFormatReader`. Sorry for the lack of details, I'm a little busy at the moment.

**Comment by odahcam** [comment]
@helloo0-0oword do you want to decode from a live camera stream or you have a specific file you want to decode?

**Comment by c0b41** [comment]
@helloo0-0oword use expo, already support barcode scanner
https://docs.expo.io/versions/latest/sdk/bar-code-scanner

**Comment by odahcam** [comment]
Well, I'm closing because of no issuer activity.
