### ISSUE TITLE
Drop text-encoding dependency (at least at Browser)

### ISSUE THREAD

**Issue by odahcam** [zxing-js/library#54]
`text-encoding` is a too heavy dependency, there's no way to support it in browser, server environments are good to go, but it destroys page load times.

Webpack `externals` option should be used as a first step to achieve that.

**Comment by odahcam** [comment]
I tryied to exclude the module import at least from browser, but I got no success:
https://github.com/zxing-js/library/blob/23e84e4d3d668f5182909f9862469ec39fd3d232/webpack.config.js#L73-L80

Any help for getting this to work would be highly appreciated.

**Comment by odahcam** [comment]
I dropped the dependency, now who wants to use it can use it as a polyfill for Node.

Also, I wanna support the Buffer class on node, to improve performance and get rid of this crazy giant polyfill.

**Comment by jainAdijain** [comment]
Hi, can we use it noe? is this resolved? and if yes then how to use this in ionic-angular project?

**Comment by odahcam** [comment]
The version without TextEncoding is published on NPM under the dev tag for now.

You can use it in your Ionic app by fetching some media stream and passing its binary value to some format reader. Subscribe on this issue for more: #38
