### ISSUE TITLE
Multiple readback operations using getImageData

### ISSUE THREAD

**Issue by yudielcurbelo** [zxing-js/library#552]
Warning: 
```
Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
```

It should come from this line of code.
https://github.com/zxing-js/library/blob/1e9ccb3b6b28d75b9eef866dba196d8937eb4449/src/browser/BrowserCodeReader.ts#L874

and should be resolved with the following change.
```
 const ctx = elem.getContext('2d', {willReadFrequently: true});
```

Warning can be reproduced in this example https://zxing-js.github.io/library/examples/multi-camera/

**Comment by Didi3333** [comment]
Hi @odahcam and @werthdavid  can you push a new version with this fix please

**Comment by werthdavid** [comment]
Will do!

**Comment by werthdavid** [comment]
plz try 0.19.3

**Comment by yudielcurbelo** [comment]
Confirmed, working as expected on `0.19.3`. Thank you @werthdavid

**Comment by werthdavid** [comment]
May I ask you to test 0.20.0 as well? I merged lots of PRs there, currently testing it myself as well

**Comment by yudielcurbelo** [comment]
All my tests passed on `0.20.0`, and doing some manual tests is also working as intended.
