### ISSUE TITLE
[CODE_128] Can't read barcode

### ISSUE THREAD

**Issue by jumafuse** [zxing-js/library#566]
Any help would be greatly appreciated.

My code basically replicates the behaviour of the test application: 

https://zxing-js.github.io/library/examples/multi-camera/

Example Image:

https://ibb.co/hWkGHzm

I can hardly read it in a blue moon under perfect conditions. It really doesn't make sense since most of the time doesn't work.

If I'm missing some configuration options that I should set somewhere, I set hints already to only CODE_128. 

I would greatly appreciate any hints.

**Comment by jumafuse** [comment]
I can offer a bounty if that helps any time dedicated to this worthwhile.

**Comment by alvarobertin** [comment]
i'm having the same issue 😞  but with EAN codes. If i find something i'll let you know

**Comment by zhanghaipeng788** [comment]
i'm having the same issue 😞 but with Codebarcodes. If i find something i'll let you know

**Comment by bbuhler** [comment]
In my case it is working with version 0.19.x but not with latest 0.20.0.

**Comment by teckel12** [comment]
@jumafuse It could be you're using the wrong camera on your scanning device (if using a phone).  it could be using a camera that doesn't support autofocus.

I forked a Vue-based library and added the capability to auto-select the most appropriate camera (one with autofocus and torch).  I also added a bunch of other features which greatly help scanning (like zoom and even manual focus capability).  Basically, the goal was for it to work as well as any native barcode scanning app.  BTW, my library can totally read your example barcode without any issues.

Here's a link to a sandbox demo.  Probably best to try it from your phone:

https://codesandbox.io/p/sandbox/vue-barcode-reader-example-pcyvsp?file=%2Fsrc%2Fcomponents%2FCameraScanner.vue%3A1%2C1

**Comment by alvarobertin** [comment]
Wow @teckel12, its working perfectly! That's what we were looking for in my team! 

Kudos to you!

**Comment by JanPolasek** [comment]
@jumafuse  Try using version 0.18.0 (I think 0.18.2 is the last one that works properly). I've pinned that version in my project as 0.18.3 broke scanning of several symbologies including EAN13 and CODE_128. Issues with EANs have been resolved in 0.20.0, but when I compared 0.20.0 and 0.18.0 side by side the former simply couldn't scan CODE_128 reliably while the latter fared much better.

**Comment by dolin-tan** [comment]
@JanPolasek  V0.18.2 Scan Code_ 128 is effective for me, although not very clever, it can barely be used. Thank you very much

**Comment by teckel12** [comment]
@JanPolasek I have no problem scanning the barcode in this issue or the one in #394 with v0.20.0.  But looking at your changes in #574 it does appear there was a typo.  I've made a comment in your code as it could be simplified further as well.

**Comment by piotr-bender-silevis** [comment]
I've used `DecodeHintType.TRY_HARDER` and it work much better on 0.20.0
