### ISSUE TITLE
How I can include this lib for browser webapp?

### ISSUE THREAD

**Issue by progressify** [zxing-js/library#63]
Hi
At this link, in library description:
https://github.com/zxing-js/library#browser

"To use from JS you need to include what you need from build/umd folder (for example zxing.min.js)."

But in repos is not present "build" folder. How I can include this lib in my project?
I use django and I want to include this in a single page for scan qrcode and barcode

**Comment by odahcam** [comment]
The repo holds the Source code, the Distribution version is published via npm/yarn you gotta install the library through them or use some CDN like unpkg to get those distribution files. 🙂

**Comment by progressify** [comment]
Thanks for you reply
I have search this file on unpkg

https://unpkg.com/@zxing/library@0.6.0

"Cannot find module "./umd/index.js" in package @zxing/library@0.6.0"

I receive this error :((

**Comment by odahcam** [comment]
I see, the file actually has the .min extension: https://unpkg.com/@zxing/library@0.6.0/umd/index.min.js

I'll try to fix this on next patch, thanks.

Also, to browse the files you can access: https://unpkg.com/@zxing/library@0.6.0/

That should be good to go.

**Comment by progressify** [comment]
Thank you.

I have resolved!

I have another question, If I want to use at same time barcode and qrcode scanner I must to declare 2 different object? or exist a mixed class?

**Comment by odahcam** [comment]
We have the MultiFormatReader. 😄 

I'll be closing now as the primary issue is solved. Feel free to open new ones.

**Comment by progressify** [comment]
Thanks
I have opened another issue for this :)

https://github.com/zxing-js/library/issues/64
