### ISSUE TITLE
1D Scan Barcode from Video Camera demo is broken

### ISSUE THREAD

**Issue by AlesRuzickaEu** [zxing-js/library#65]
Demo on URL `https://zxing-js.github.io/library/examples/barcode-camera/` can't find (404) linked script file (`index.min.js`), therefore i just get additional error `ZXing is not defined` and nothing works.

**Comment by odahcam** [comment]
Looks like it is not the only one. 😱 

You can still download and run the demo page locally.

Ideally we should auto-generate the demo pages with some script, but I didn't find how to do that properly yet.

**Comment by odahcam** [comment]
I believe I solved it in my last commit, now I'm importing the dev version available at unpkg CDN.
