### ISSUE TITLE
Replace TextEncoding by Buffer on Node.js

### ISSUE THREAD

**Issue by odahcam** [zxing-js/library#68]
Make use of the Buffer class on node, to improve performance and get rid of any TextEncoder/TextDecoder (browser will still use TextEncoder and TextDecoder).

**Comment by pvdstel** [comment]
Do you mean replacing the `text-encoding` dependency with the built-in Node `Buffer` class in `StringEncoding.ts`?

**Comment by odahcam** [comment]
Exactly that! If you wanna make a PR, we can probably merge it very soon, probably by next minor version. 😄

**Comment by lookfirst** [comment]
Since PR #73 was closed and locked, here is the 'new' issue that was referenced to be 'created'. No need to create a new one since it is already open, right?

@odahcam will you close and lock this one too?

**Comment by lookfirst** [comment]
To be clear, the text-encoding dependency produces a warning during `npm install` because the repo is archived on github and the source code is no longer supported.

**Comment by lookfirst** [comment]
#54 as well

**Comment by odahcam** [comment]
Sorry, no intend to offend no one here, as enraged people are not welcome too.

AS the description of the issue says:

> Make use of the Buffer class on node, to improve performance and get rid of any TextEncoder/TextDecoder (browser will still use TextEncoder and TextDecoder).

This is already done, so closing.

As you did some digging, at this point you must have realized that I already tried lots of times to get rid of `text-encoding` for browser and, currently, it is not possible. That's one of the reasons I wanna split this library into two packages, core and browser; each one with it's own dependencies.

Also, `text-encoding` is a optional dependency, you're completely free to not use it and disable the warning. :)

**Comment by lookfirst** [comment]
Why not just copy the source code into this project? The other project is archived and might go away. You're risking that by continuing to depend on it. The license is open and thus can be done.

**Comment by odahcam** [comment]
> Why not just copy the source code into this project?

What difference it will make?

> The other project is archived and might go away. 

It cannot be erase from NPM neither from internet.

> You're risking that by continuing to depend on it. The license is open and thus can be done.

Ok, we use the same version for the past two years, it's more stable than this library itself, and we will probably continue to use that version, no matter if new ones shows up.

----

You could make a fork of the lib and continue to maintain it and we could start using this fork as needed. But if I was you, I wouldn't worry about that.
