### ISSUE TITLE
Unable to import the library in requirejs

### ISSUE THREAD

**Issue by TBPriya** [zxing-js/library#72]
I am trying to import this library using require js. But i am unable to do it.  At the same location I have other libraries. I am able to import them, but not his library. Is is not possible to load this using requirejs ?

I am using the index.min.js. Please help me to import your library using requirejs

**Comment by odahcam** [comment]
Hello, what's the error you're getting?

**Comment by TBPriya** [comment]
Hi,
This is how I try to import the that index.min.js from https://unpkg.com/@zxing/library@0.7.0-dev.058aea/umd/index.min.js
define(['zxindex.min'], function (indexmin) {
     console.log(indexmin);
});

I have renamed index.min.js to zxindex.min.js and impoting in one of my module. 
when I access it 'indexmin' I get undefined. Actually, I want to access the   ZXing.BrowserQRCodeReader('video'); something like   
const codeReader = new ZXing.BrowserQRCodeReader('video'); 
But I am not able to do that, as the js does not return any object. require js expects something to be returned from js to access the functions.

So temporarily I have changed your js to return ZXing QRCodeReader and BarCodeReader objects. I have updated first few lines of your js to 
```
define([],function(){
**var xing ={};**
!function(t, e) {
     t.ZXing = e()
    const codeReader = new ZXing.BrowserQRCodeReader('video');
    const barCodeReader = new ZXing.BrowserBarcodeReader('video');
    **xing.barCodeReader = barCodeReader;
    xing.qrCodeReader = codeReader;**
}(window, function() {     
    return function(t) {
             var e = {};
```
and at the end returning the object to return

```
return **xing**;
});
```
Is there any better way to use ZXing.BrowserQRCodeReader and ZXing.BrowserBarcodeReader ? Please let me know

Thanks,
Priya

**Comment by odahcam** [comment]
I can't say what's the problem, but the AMD is working fine:

![image](https://user-images.githubusercontent.com/3942006/43031175-b373419a-8c72-11e8-9907-c0abff270a06.png)

I'm going to close this as this is not a problem with the package itself.
