### ISSUE TITLE
Add flag to enable/disable logging

### ISSUE THREAD

**Issue by gjavi1** [zxing-js/library#74]
The `BrowserCodeReader` class has multiple lines for logging errors:

https://github.com/zxing-js/library/blob/af16fdb2a72b331394dfe22b549703bdfefcae90/src/browser/BrowserCodeReader.ts#L257

https://github.com/zxing-js/library/blob/af16fdb2a72b331394dfe22b549703bdfefcae90/src/browser/BrowserCodeReader.ts#L259

https://github.com/zxing-js/library/blob/af16fdb2a72b331394dfe22b549703bdfefcae90/src/browser/BrowserCodeReader.ts#L262

There should be an option to enable/disable this.

**Comment by odahcam** [comment]
In fact, they should be erased. 😅

**Comment by odahcam** [comment]
Solved in 5f78d5.
