### ISSUE TITLE
Decoding not consistent

### ISSUE THREAD

**Issue by francoberton** [zxing-js/library#78]
Hi,
I have a problem with the decoding of a Qr code image, that i'm passing as a base64 string to the decodeFromImage function, as following

```  
 const codeReader = new BrowserQRCodeReader();
    codeReader.decodeFromImage(undefined, this.state.qrImage)
      .then(
        (result) => { this.showSuccessMessage('The QR is valid!'); console.log(result.getResultMetadata()); }
      )
      .catch(
        () => this.showErrorMessage('The QR is unreadable.')
      );
```  

When I execute this code multiple times on the same image, the result is not consistent. Sometimes the decoding works and it return the correct result, but other times it throws an exception, and prints in the console the following errors

```
checksum or format error, trying again... Error
    at Decoder.correctErrors (Decoder.js?958e:154)
    at Decoder.decodeBitMatrixParser (Decoder.js?958e:125)
    at Decoder.decodeBitMatrix (Decoder.js?958e:70)
    at QRCodeReader.decode (QRCodeReader.js?680d:64)
    at BrowserQRCodeReader.BrowserCodeReader.readerDecode (BrowserCodeReader.js?0615:254)
    at BrowserQRCodeReader.BrowserCodeReader.decodeOnce (BrowserCodeReader.js?0615:229)

BrowserCodeReader.js?0615:233 true Error
    at Decoder.correctErrors (Decoder.js?958e:154)
    at Decoder.decodeBitMatrixParser (Decoder.js?958e:125)
    at Decoder.decodeBitMatrix (Decoder.js?958e:70)
    at QRCodeReader.decode (QRCodeReader.js?680d:64)
    at BrowserQRCodeReader.BrowserCodeReader.readerDecode (BrowserCodeReader.js?0615:254)
    at BrowserQRCodeReader.BrowserCodeReader.decodeOnce (BrowserCodeReader.js?0615:229)
```

I wait for an answer. Thank you

**Comment by werthdavid** [comment]
I'm not exactly sure what kind of answer you're expecting. The Decoder goes through a lot of steps to detect if a given image contains a valid QR-code, it seems that your code fails in the error-correction step. If you want a qualified answer it would help if you could provide the image that causes the actual problem along with information about which version of the library you used, the platform (node, browser, ionic), browser etc.

**Comment by patrickfav** [comment]
This is maybe related. My experience is not that it is inconsistent with the same QR code, but totally inconsistent with different codes. For example this one reads fine:

![qr2](https://user-images.githubusercontent.com/2980711/43764520-ecf7ffdc-9a2d-11e8-8208-543a2eb02749.png)


and this one is not

![qr24t](https://user-images.githubusercontent.com/2980711/43764527-f3707466-9a2d-11e8-91ce-08e11e68bd24.png)


(only in Chrome BTW, these PNGs do not read on FF or Edge)

I get

```javascript
true Error: No MultiFormat Readers were able to detect the code.
    at MultiFormatReader.decodeInternal (MultiFormatReader.js:179)
    at MultiFormatReader.decode (MultiFormatReader.js:63)
    at HBBrowserQRCodeReader.BrowserCodeReader.readerDecode (BrowserCodeReader.js:254)
    at HBBrowserQRCodeReader.BrowserCodeReader.decodeOnce (BrowserCodeReader.js:229)
    at HTMLImageElement.me.imageLoadedEventListener (BrowserCodeReader.js:174)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:3995)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at ZoneTask.invokeTask [as invoke] (zone.js:496)
```

and using this reader config


```typescript
class MyBrowserQRCodeReader extends BrowserCodeReader {
  private readonly reader2: MultiFormatReader;

  public constructor(timeBetweenScansMillis: number = 350) {
    const decoderHintMap = new Map<DecodeHintType, any>();
    decoderHintMap.set(DecodeHintType.TRY_HARDER, true);
    decoderHintMap.set(DecodeHintType.POSSIBLE_FORMATS, [BarcodeFormat.QR_CODE]);

    const reader = new MultiFormatReader();
    reader.setHints(decoderHintMap);

    super(reader, timeBetweenScansMillis);
    this.reader2 = reader;
  }

  protected decodeBitmap(binaryBitmap: BinaryBitmap): Result {
    return this.reader2.decodeWithState(binaryBitmap);
  }
}
```

I decode with the object url

`URL.createObjectURL(file);`

any ideas?

**Comment by odahcam** [comment]
I read both codes using production build running in one of the company I work projects; https://minhahavan.com/ and the scanner reads both codes fine. 🤔

**Comment by patrickfav** [comment]
@odahcam thanks for the feedback. Do you have any tips what config to use for simple file based reading?

**Comment by odahcam** [comment]
If you're not in browser, you can take a look at the `src/tests` folder, there we scan A LOT of barcode files to ensure the lib is safe. 🙂

**Comment by patrickfav** [comment]
Unfortunately we are in the browser context.

**Comment by odahcam** [comment]
So we have a lot less examples. 🙁 

I can try to help based on what you have now, can you share some piecce of code?

**Comment by patrickfav** [comment]
Thank you very much for the offer!

Here is a gist with the important parts of our QR service:

https://gist.github.com/patrickfav/46092f9b6e3fde8833cfcc75ccc9075b

If you have time maybe you could point out obvious issues?

**Comment by odahcam** [comment]
I couldn't find any very obvious errors, but I'm a little busy at the moment. I can offeryou an working example you can find in the docs:

```javascript
const img = document.getElementById('img')

codeReader.decodeFromImage(img).then((result) => {
    console.log(result)
    document.getElementById('result').textContent = result.text
}).catch((err) => {
    console.error(err)
    document.getElementById('result').textContent = err
})
```

source: https://github.com/zxing-js/library/blob/af16fdb2a72b331394dfe22b549703bdfefcae90/docs/examples/qr-image/index.html#L1

(The demo just don't work online, locally it works fine andyou can use it)

I see you're using Base64 encoded images and I think that there's really a bug in the code, that's not that good yet. You can create your own image element and trigger the `decodeOnce` on image's `onload` event. E.g.:

```javascript
const imageElement = document.createElement('img');
imageElement.width = 200;
imageElement.height = 200;

imageElement.addEventListener('load', () => scanner.decodeFromImage(imageElement));
imageElement.src = imageUrl;
```

I hope that it helps.

**Comment by odahcam** [comment]
If there's no more things to discuss I'll be closing this guy here soon. Thx.
