### ISSUE TITLE
Constant Console Logs

### ISSUE THREAD

**Issue by michael-pearson** [zxing-js/library#81]
I'm getting constant console logs in both my application, and on the demo site listed in your documentation. Would it be possible to have a verbose mode configuration parameter of some sort to turn these off?

```
true Error
    at t.selectBestPatterns (FinderPatternFinder.ts:595)
    at t.find (FinderPatternFinder.ts:181)
    at t.detect (Detector.ts:84)
    at t.decode (QRCodeReader.ts:75)
    at e.t.readerDecode (BrowserCodeReader.ts:278)
    at e.t.decodeOnce (BrowserCodeReader.ts:254)

BrowserCodeReader.ts:259 not found, trying again...
```

**Comment by odahcam** [comment]
What version of `@zxing/library` are you using?

**Comment by michael-pearson** [comment]
I've actually decided to use a different library now (I was also having trouble with stopping and starting the capture where it would just stop scanning for codes but that was probably a fault on my part), and I can't remember the version that I installed. It would have been the newest version available on NPM at the point that I made the post above. However, as I mentioned, it is also doing that on the demo page provided in the docs, [https://zxing-js.github.io/library/examples/qr-camera/](https://zxing-js.github.io/library/examples/qr-camera/).

**Comment by odahcam** [comment]
Allright, thanks, the LTS version is already free of spam logs btw.

**Comment by michael-pearson** [comment]
Where is the LTS version? The version available on NPM gives me the console errors, as does the version on your demo site.

**Comment by odahcam** [comment]
Sorry, I forgot to refer; dupe of #74.
