### ISSUE TITLE
ArgumentException: element with id 'video' not found

### ISSUE THREAD

**Issue by bestbelief** [zxing-js/library#86]
hello, I encountered a mistake when I set the camera back by default.it is "element with id 'video' not found"。Could you help me to see what might be wrong?

html:
 <video id="video" width="300" height="200" style="border: 1px solid gray"></video>

component.ts:
 getBackVideo() {
        const codeReader = new BrowserQRCodeReader();
        codeReader.decodeFromInputVideoDevice(undefined, 'video')
        .then(result => console.log(result))
        .catch(err => console.error(err));
      }

**Comment by bestbelief** [comment]
Sorry to bother you. I already know where I was wrong.

**Comment by odahcam** [comment]
That's fine.
