### ISSUE TITLE
Which package to use for production?

### ISSUE THREAD

**Issue by memic84** [zxing-js/library#89]
Hi Guys,

This is the best scanner in JavaScript i have come across after a long search.
I do have one question, i was using **@zxing-js/library** the CDN and switched to the npm package.
However i get the message: `Deprecated symbol used, consult docs for better alternative`. 

I presume that i should use the @zxing-js/browser, but because there are no docs yet and it's new i thought that this is more stable.

What do you advise? I am using the BrowserQRCodeReader and the BrowserBarcodeReader from the library. Will the support stay in the library?

**Comment by odahcam** [comment]
Yeah, we're still supporting the library until the browser package is production ready. Anyway, I've never seen that depecration message, can you share some code/demo so I can take a look at that?

**Comment by memic84** [comment]
I think it's because of the @deprecated in BrowserCodeReader etc.. 
```
/**
 * @deprecated Moving to @zxing/browser
 *
 * QR Code reader to use from browser.
 */
```

So it's logical that webstorm is giving the following messages.

![image](https://user-images.githubusercontent.com/3043840/45414662-3408ec00-b67c-11e8-9ae6-b9f96262f730.png)

![image](https://user-images.githubusercontent.com/3043840/45414700-43883500-b67c-11e8-8ced-8463a3df9a9b.png)

My question has been answered, thanks.
This can be closed for now.

**Comment by memic84** [comment]
question is answered.

**Comment by odahcam** [comment]
Wow, what a nice feature from Webstorm! I didn't know that this deprecation it would be so shoking in certain IDEs. 😄 

As you already know, that's no problem with the code itself, the deprecation is just to alert users that in a near future this class/method will no longer exist in this package.

Thanks for the feedback btw.

**Comment by odahcam** [comment]
Just for anyone wondering which package to use in 2020, I think you can give the browser one a shot: https://github.com/zxing-js/browser/releases/tag/v0.0.1-preview.1
