### ISSUE TITLE
Cannot create a EAN13 barcode reader

### ISSUE THREAD

**Issue by tbhattacharya** [zxing-js/library#9]
I am trying to create a EAN13 barcode reader.
But when i use onst codeReader = new BrowserCodeReader(), the constructor asks for a Reader. But there are no readers for EAN13

**Comment by odahcam** [comment]
I've made this fork to fix a TypeScript publish/deploy issue from @aleris. I think it would be more prudent to ask in the source repo @aleris/zxing-typescript about this issue.

You can make a PR here if want to implement that. Unfortunatelly I'm a little out of time to implement that reader for you now.

My objective here is to merge it back on @aleris repo or to bring his repo to this organization if he wants, but I didn't ask for any of these options yet. 😅

**Comment by odahcam** [comment]
Solved by #37

**Comment by odahcam** [comment]
#37 resolves
