### ISSUE TITLE
not working in xiaomi browser?

### ISSUE THREAD

**Issue by JacCheng** [zxing-js/library#91]
not working in xiaomi browser?it is Black screen...

**Comment by odahcam** [comment]
Can you provide OS, Browser and Library version? The approach you're using would be great too.

**Comment by odahcam** [comment]
I just don't know how to test it and caniuse.com does not provides me a compatibility table for this browser. Any ideias if it supports `getUserMedia`?

**Comment by dartess** [comment]
Any `mediaDevices.getUserMedia` promises never resolving or rejecting.
I suggest to burn Mi Browser.
