### ISSUE TITLE
Allowed to enable zoom

### ISSUE THREAD

**Issue by CKESSLER** [zxing-js/library#94]
For some small sized datamatrix or qrcode, base zoom is not enougth to read them easily.
Is it possible to enable the zoom with a parameter for the function decodeFromInputVideoDevice ?
Below an example of zoom implementation that works  in BrowserCodeReader.js  /  BrowserCodeReader.prototype.decodeFromInputVideoDevice
```
....
me.videoElement.play();

const track = stream.getVideoTracks()[0];
me.videoElement.addEventListener('loadedmetadata', (e) => {
    window.setTimeout(() => (
        onCapabilitiesReady(track.getCapabilities())
    ), 500);
});

function onCapabilitiesReady(capabilities) {
    if (capabilities.zoom) {
        track.applyConstraints({
        advanced: [{zoom: capabilities.zoom.max}]
        })
        .catch(e => console.log(e));
    }
}
```

**Comment by odahcam** [comment]
I think we can do something about that, we just need to keep in mind that not every barcode will be entire visible inside the zoomed image. Wouldn't `hints` be more appropriated than parameters for that feature?

**Comment by CKESSLER** [comment]
Sorry, i  don't understand what is a "hint" in this case 🤔

Le lun. 24 sept. 2018 à 17:10, Luiz Machado <notifications@github.com> a
écrit :

**Comment by CKESSLER** [comment]
Can i help you with this feature ? 
I have some time to invest in this project.

**Comment by odahcam** [comment]
Of course! Feel free to investigate, I'm a little busy btw so a little help would be awesome. :)

**Comment by CKESSLER** [comment]
After some tries, i think it's better to not implemented this options.
It's quite easy to manage the zoom :

`navigator.mediaDevices
        .getUserMedia({
          video: { facingMode: 'environment' }
        })
        .then(async stream => {
          await this.sleep(250)
          // camera device found
          this.deviceFound = true
          // get device capabilities (zoom and others)
          let videoTrack = stream.getVideoTracks()[0]
          if (typeof videoTrack.getCapabilities !== 'undefined') {
            let capabilities = videoTrack.getCapabilities()
            // set zoom params
            if ( 'zoom' in capabilities) {
              videoTrack.applyConstraints({
                 advanced: [{ zoom: this.zoom }]
              })
            }
          }
        })
        .catch(error => {
          // no media device found
        })
    },`

**Comment by odahcam** [comment]
Maybe the lib could return the device capabilities if available and allow the user to apply them on the videioTrack. 🤔

**Comment by sudoman98** [comment]
I am trying to scan qrcode from medium distance( 10 meters). I wanted to use the zoom of camera to implement it. 
I use this code for the zoom, it works well in Chrome  on Android devices, but when i try to use it on safari it doesn't work, it seems that in safari zoom isn't present in capabilities. Have you any idea how I can solve that? 
This is my code:

 ```
   if (!iOS) {
        var constraints = {
        audio: false, 
        video: {
            deviceId: {exact: final.deviceId},
            focusDistance:5,
            frameRate: {
                            min: 10
                        }
            }
        };
     }
     else{
         var constraints = {
        audio: false, 
        video: {
            facingMode: 'environment',
            focusDistance:5,
            frameRate: {
                            min: 10
                        }

            }
        };
      }
  tooglecamera(constraints);

      function tooglecamera(constraints){
          navigator.mediaDevices.getUserMedia(constraints).
           then(async mediaStream => {
                                      document.querySelector('video').srcObject = mediaStream;
                                      // setscanner();
                                      await this.sleep(1000)
                                      const track = mediaStream.getVideoTracks()[0];
                                      const capabilities = track.getCapabilities();
                                      const settings = track.getSettings();

                                      const input = document.querySelector('input[type="range"]');

                                      // Check whether zoom is supported or not.
                                      console.log(capabilities);
                                      console.log('--------');

                                      console.log(track.getSettings());
                                      if (!('zoom' in capabilities)) {
                                        alert('Zoom is not supported by ' + track.label);
                                      }

                                      // Map zoom to a slider element.
                                      input.min = capabilities.zoom.min;
                                      input.max = capabilities.zoom.max;
                                      input.step = capabilities.zoom.step;
                                      input.value = settings.zoom;
                                         input.oninput = function(event) {
                                        track.applyConstraints({advanced: [ {zoom: event.target.value} ]});
                                      }
                                     
                                      input.hidden = false;

                                    }).catch(function(err) {
                                                                    console.log(err);
                                                            });

}
```
