### ISSUE TITLE
Failed to execute 'drawImage'  on 'CanvasRenderingContext2D'

### ISSUE THREAD

**Issue by henioStraszny** [zxing-js/library#97]
After second attempt to scan a QR code, I see in console following error:

```
ERROR TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'
    at BrowserCodeReader.push../node_modules/@zxing/ngx-scanner/esm5/zxing-ngx-scanner.js.BrowserCodeReader.createBinaryBitmap (zxing-ngx-scanner.js:175)
    at BrowserCodeReader.push../node_modules/@zxing/ngx-scanner/esm5/zxing-ngx-scanner.js.BrowserCodeReader.decode (zxing-ngx-scanner.js:157)
    at zxing-ngx-scanner.js:147
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:13842)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:496)
    at ZoneTask.invoke (zone.js:485)
    at timer (zone.js:2054)
```

Despite that, scanner seems to work fine, I'm able to retrieve decrypted data.

**Comment by machinaeXphilip** [comment]
maybe this helps investigating, maybe not:

i did have the same issue on the first reset() call. 
it seemed to be connected with me using two BarcodeScanner instances at the same time ( one ZXing.BrowserQRCodeReader(), one for ZXing.BrowserBarcodeReader() ) on the same <video> element in the dom.

after giving each of them their own video element in the dom the error messages stopped.

when then trying to call reset() from one CodeReader to the other (see code below) the error starts again, even with two different video objects in the DOM.

I could not find out how to use MultiFormatReader within the Browser. I suppose that would actually be the right way to approach this. 

        let selectedDeviceId;
        const codeReader = new ZXing.BrowserQRCodeReader()
        const codeReaderBC = new ZXing.BrowserBarcodeReader()

        codeReaderBC.getVideoInputDevices()
        .then((videoInputDevices) => {
          console.log("VideoInputDevices:");
          console.log(videoInputDevices);
            const sourceSelect = document.getElementById('sourceSelect')
            selectedDeviceId = videoInputDevices[0].deviceId
            console.log(selectedDeviceId);
            if (videoInputDevices.length >= 1) {
                videoInputDevices.forEach((element) => {
                    const sourceOption = document.createElement('option')
                    sourceOption.text = element.label
                    sourceOption.value = element.deviceId
                    sourceSelect.appendChild(sourceOption)
                })

                sourceSelect.onchange = () => {
                    selectedDeviceId = sourceSelect.value;
                };

                const sourceSelectPanel = document.getElementById('sourceSelectPanel')
                sourceSelectPanel.style.display = 'block'
            }
        })
        .catch((err) => {
            console.error(err)
        })

        codeReader.getVideoInputDevices()
            .then((videoInputDevices) => {
              console.log("VideoInputDevices:");
              console.log(videoInputDevices);
                const sourceSelect = document.getElementById('sourceSelect')
                selectedDeviceId = videoInputDevices[0].deviceId
                console.log(selectedDeviceId);
                if (videoInputDevices.length >= 1) {
                    videoInputDevices.forEach((element) => {
                        const sourceOption = document.createElement('option')
                        sourceOption.text = element.label
                        sourceOption.value = element.deviceId
                        sourceSelect.appendChild(sourceOption)
                    })

                    sourceSelect.onchange = () => {
                        selectedDeviceId = sourceSelect.value;
                    };

                    const sourceSelectPanel = document.getElementById('sourceSelectPanel')
                    sourceSelectPanel.style.display = 'block'
                }
            })
            .catch((err) => {
                console.error(err)
            })

    function startZxingJsScan(){

          codeReaderBC.decodeFromInputVideoDevice(selectedDeviceId, 'zxingvideo').then((result) => {
              console.log(result)
              dispatchBarcodeEvent(result)

              codeReader.reset();
              codeReaderBC.reset();

          }).catch((err) => {
              console.error(err)
          })
 
        codeReader.decodeFromInputVideoDevice(selectedDeviceId, 'zxingvideo2').then((result) => {
            console.log(result)
            dispatchBarcodeEvent(result)
        
            codeReaderBC.reset();
            codeReader.reset();

        }).catch((err) => { 
            console.error(err)
        })

    }

**Comment by lipeng-27** [comment]
Directly assign the device and change the device, as below:
this.currentDevice = device;
So I commented this code, then it works.
//this.scanner.changeDevice(device);

**Comment by odahcam** [comment]
Please, use https://github.com/zxing-js/ngx-scanner for Angular projects, thanks.
